### ISSUE TITLE
Use "Group Publisher" to publish Kiwix JS extension for Chrome

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#1031]
For the moment we have only an individual developer account, which is on my name, so only me can publish, which is not optimal. It seem the solution is to follow https://developer.chrome.com/docs/webstore/group-publishers/

**Comment by kelson42** [comment]
@Jaifroid Does that look appropriate to you?

**Comment by Jaifroid** [comment]
It does look appropriate and useful. We should have as close as possible to org-level control over all the assets published, so that we don't get into the situation of one maintainer leaving (or becoming disgruntled) and locking everyone else out. Not saying this would happen with the Chrome case, but it's just a good general principle.

I suppose you need to initiate this, right?

**Comment by Jaifroid** [comment]
@kelson42 This issue is assigned to me, but I think I can't do much about it as you control the publishing account. Let me know if there is anything I can do.

**Comment by kelson42** [comment]
@kelson42 Yes, give me a week.

**Comment by Jaifroid** [comment]
> @kelson42 Yes, give me a week.

Of course, no rush, I'm not preparing another release yet!

**Comment by Jaifroid** [comment]
Considering a new release probably in a couple of weeks after some PRs are finished. See #1094.

**Comment by Jaifroid** [comment]
@kelson42 Just a quick check to ask whether you want to switch the Chrome Extension Store owner for this app to a group publisher before next release (coming soon after testing is complete), or leave it till after.

**Comment by Jaifroid** [comment]
Bumping to v4.0.
As part of #1118, I need to translate the Chrome Store entry to French and Spanish. I've already done this for the Mozilla Store. I'll do Edge Store next, but it would be good to have the necessary access to be able to complete it myself for Chrome when possible.

**Comment by Jaifroid** [comment]
@kelson42 In the light of #1143 and #1118, do you think it might be possible for this issue to be completed in time for v3.11? My main concern is not so much the publishing as having access to the Store entry so that I can translate it to French and Spanish, now that we have UI in those languages. However, I know you're in a race to get the other app releases out, so this could wait till 4.0 if there is no time to get it done.

**Comment by Jaifroid** [comment]
@kelson42 FYI my timeline for releasing v4.0 (#1186) is probably around two weeks. As they say, "a stitch in time saves nine"!

**Comment by Jaifroid** [comment]
FYI v4.0 is next on my plate, but I'm a bit tired from the v3 PWA release, so it'll probably be another week (there are improvements that need to be backported from the PWA).

**Comment by Jaifroid** [comment]
@kelson42 Is this issue still wanted, or should I close it? Personally, I don't mind either way and I can see a good argument for having you involved in the publishing of new versions, so long as it's not a hassle for you each time we release.

**Comment by Jaifroid** [comment]
And finally I am registered! 😊
