### ISSUE TITLE
ZIM backend : Title search should be case-insensitive and diacritic-insensitive

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#117]

**Comment by peter-x** [comment]
Does that really work for zim? AFAIK, title lists in zim files are not normalized, so this feature requires a change to the zim format and not only the reader backend.

**Comment by mossroy** [comment]
You're right, I was not sure of myself when I did it.
But the case-insensitivity seemed to work : it finds titles starting with 'B' when I type 'b', for example.
But I did not test a lot. Especially with accents or other special characters (I tested only on the "Ray Charles" archive, which is in English).
Feel free to reopen this bug, or create another one if necessary.

NB : You can easily test by cloning the "master" branch, open it on a desktop Firefox (or Chromium), and select a ZIM file

**Comment by mossroy** [comment]
After talking to kelson42, Kiwix search is currently case sensitive (even if it tries to replace upper and lower case for the first character in case the search does not give any result. Cf Reader::searchSuggestions and Reader::searchSuggestionsSmart in https://sourceforge.net/p/kiwix/kiwix/ci/master/tree/src/common/kiwix/reader.cpp).

**Comment by mossroy** [comment]
I move this issue in v2.1, because it can not be done without an evolution of the OpenZIM file format.
For v2.0, we might implement #124

**Comment by mossroy** [comment]
The diacritics make finding the article sometimes complicated.
For example, on a French wikipedia archive, you have to type the accents properly in order to find your article. If you omit them, the article is not found.
@kelson42 : is it the way it works on other Kiwix implementations too? If it's the case, we maybe should warn the user about that?
Or did you find a workaround until the OpenZIM file formats integrates a "normalized" index? (like the upper/lowercase variants).

**Comment by kelson42** [comment]
@mossroy For now no solution to that problem. On other versions of Kiwix, we just try with/without uppercase on the first letter, but there is for now no other way to have a fully diacritics insensitive solution.

**Comment by Jaifroid** [comment]
@mossroy I think we could close this issue. We dealt with the case-insensitivity issue (we now have pretty good pseudo-case-insensitivity). The only reason to keep this open is if you are interested in adding diacritic insensitivity to Kiwix JS. It would be a bit impractical to do with our current search method because we would need several variants of every vowel and of some consonants, which would rapidly lead to exponential search "variants". It *could* be done with the brute-force method of searching through a given range of titles and testing each one with a non-case-sensitive regex constructed like /m[eéè]th[oôöóò]d/ (this would require my regex search algorithm, and it would need further work on it).

But as I suspect we've done enough on this, I would recommend closing this issue now.

**Comment by mossroy** [comment]
I agree.
Handling diacritics could have been implemented efficiently if there was a "normalized" title index in ZIM files (i.e. with diacritics removed). But it's not the case.

Supporting the xapian full-text search is the only viable solution. Hopefully it will come with the emscripten kiwix-lib
