### ISSUE TITLE
Display a spinner when the user clicks on a link inside an article (in ServiceWorker mode)

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#135]
It can take a few seconds to display the new article : the user needs to have a visual feedback that his click is being processed.

One approach to test is to catch the onclick event on all the iframe, and then find out if the target of this click event is inside a `<a href>` tag. In this case, the spinner should be visible (and disappear when the new article appears)

**Comment by Jaifroid** [comment]
@mossroy, I was about to open a new issue for this (lack of "Reading article" + spinner when user clicks on a link in Service Worker) when a vague memory of having seen something like it before led me here. So, this is just to report that this (minor) issue is ongoing in Service Worker mode to date (tested today on Chromium). But I would label this a bug rather than an enhancement. Surely the intended behaviour is to give feedback to the user?

**Comment by mossroy** [comment]
In ServiceWorker mode, I would hope that the browser handles that by itself.
When the user clicks on a link inside the iframe, it should be the same behavior as when you click on a hyperlink in a web page : the browser indicates it is busy until the page is loaded, with indicators like explained here : https://www.stevesouders.com/blog/2013/06/16/browser-busy-indicators/
Obviously, these busy indicators don't show up here : I'd like to understand why, before implementing our own indicators. Maybe there would be a way to enable these built-in indicators, which would be much better.
Is it because we are in a iframe? Because the requests are handled by a ServiceWorker?

**Comment by Jaifroid** [comment]
This issue was incidentally solved by #493. The spinner now shows when a user clicks on a link in SW mode. There are aspects that could be made more consistent, but we have #419 for that.
