### ISSUE TITLE
Zooming with the fingers should only zoom the article content, not the UI (menus, bottom bar etc)

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#163]

**Comment by Jaifroid** [comment]
@mossroy , @sharun-s : I tried to research ways to enable pinch-to-zoom only for the iframe viewport, but nothing I found works for iframes, and the meta viewport tag zooms the entire interface as noted above.

So, as a workaround and also for non-touchscreen devices, I've added zoom buttons and functionality to the bottom toolbar in commit https://github.com/kiwix/kiwix-js/commit/ad03a435e26e6c2df9bd92f323903ce15bf993f5 .

The code is relatively simple and zooms the percentage font-size on the contentDocument's body tag. It wouldn't be hard to backport into main. Screenshot shows this in FFOS with the document zoomed 250%. Pretty essential for anyone with presbyopia :-) 

![image](https://user-images.githubusercontent.com/4304337/29703260-b97a7fc2-896c-11e7-881d-79837b01b78a.png)

**Comment by Jaifroid** [comment]
I've worked out a solution for this, and I think it is important for accessibility.

Enabling zoom of iframe with pinch gestures (but without reflow) has to be programmed manually, but there is code that is quite easy and can more or less be copied and pasted from https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures. The functions could mostly be placed in `uiUtil.js`, to avoid cluttering `app.js`. Zoom of the application viewport is prevented by applying `touch-action: none;` style rule to the `body` element in `index.html`.

The actual zoom of the iframe contents would be done with style properties `transform: scale(x%)` and `transform-origin: top left` (or `top right` for RTL languages) styles applied to the iframe, with the scale percentage determined by the pinch. It's possible that in some browsers the transforms would have to be applied to the html element of the article document rather than to the iframe (needs testing).

NB this is distinct from zoom with reflow. To achieve that, it's necessary to apply a `font-size: xx%` rule to the `body` tag of the article, but this is slow and not suitable for a pinch action (because the entire article is reflowed). It is more suitable to a zoom button or keyboard action., as a value applied to every document on load (a global relative font size setting). In browsers that support the non-standard `zoom` css property (which is actually all browsers except Firefox) a slightly more satisfactory zoom with reflow can be achieved by using `zoom: xx%` on the html element. This also zooms images in proportion to the font zoom, but otherwise is very similar to changing the relative font size of the body element.

**Comment by Jaifroid** [comment]
I worked on the above solution in Kiwix JS Windows, but could find no way of making it work properly in Firefox, Edge Legacy or IE11. It works very wel in Chrome and Edge. 

The issue in the former browsers is that it's not possible to prevent the browser from processing pinch-zoom events in the app without also preventing it from using touch gestures in the iframe's contents. So, while we can programme a graceful zoom in or out using pinch gestures, it is at the loss of being able to pan up / down / left / right with touch. Effectively we'd have to programme all these gestures.

In Chromium browsers, preventing the default pinch-zoom gesture does not prevent other touch gestures, so we only have to programme pinch-zoom (with the aim of zooming only the contents of the iframe, not the chrome surrounding it).

While I have left the new code in Kiwix JS Windows, because the PWA can use it, I don't recommend including it in Kiwix JS, because it is not a universal solution and does not add much to the native pinch-zoom gestures. The only difference is that the chrome is also zoomed with the native gesture. In the end, this makes very little difference to the user. The text is not reflowed with this solution (I already provide that functionality with buttons).

**Comment by Jaifroid** [comment]
@mossroy I'm closing this issue given my investigations above. **Reflowed** "zoom" is perfectly viable by setting global font-size percentages, but is only suitable for buttons, not for finger gestures. Feel free to re-open if I've omitted something.
