### ISSUE TITLE
Replace the XZ decoder with https://github.com/yurevich1/xz-pure-js-web-worker

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#259]
https://github.com/yurevich1/xz-pure-js-web-worker
It's also an asm.js (probably generated with emscripten).
It runs natively inside a webworker, which might improve performance.
It also might change the memory consumption (to be tested : it might be better, it might be worse)

**Comment by Jaifroid** [comment]
Interesting. Yes, it is generated with EMSCRIPTEN and it uses asm. It seems geared to decompressing (and compressing) serially the full file into a Uint8Array rather than reading bits of data from the file. But as the decompressor is entirely minified and there seems to be no documented API other than the example given, it's hard to tell...

**Comment by mossroy** [comment]
Decompressing the whole file is obviously not an option for us.
Maybe we could open an issue on this repo to ask if it might be enhanced for that?

**Comment by mossroy** [comment]
I've created https://github.com/yurevich1/xz-pure-js-web-worker/issues/1 and https://github.com/yurevich1/xz-pure-js-web-worker/issues/2 for that

**Comment by mossroy** [comment]
I close this as wontfix, as I have no news from the maintainer of xz-pure-js-web-worker on yurevich1/xz-pure-js-web-worker#1
