### ISSUE TITLE
Which repository should hold OS-specific code for abstractFilesystemAccess?

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#264]
Some quick advice, please, @mossroy . I've mentioned before that I want to write a UWP-specific version of abstractFilesystemAccess, in order to take advantage of the Future Access List in UWP and allow easier selection of split-file ZIMs (by selecting the directory that contains them, rather than selecting each split part one-by-one). Currently abstractFilesystemAccess contains OS-specific code (Firefox OS) for legacy reasons, and that is completely understandable. But it raises the question of where UWP-specific code should go:

* I could do a test in abstractFilesystemAccess to branch in one direction for FFOS and another for UWP, so that the library abstracts the filesystem of either of these supported OS's;
* Or, as there is a specific repository for the UWP app, I could replace abstractFilesystemAccess entirely in the kiwix-js-windows repo and leave it untouched in yours.

Happy either way, but I suspect it depends on where you seeing the FFOS stuff ending up in the future.

**Comment by mossroy** [comment]
I'll need to give you a more global background of how it works :

There are currently 2 ways to find ZIM files from the end-user perspective : 
- on FirefoxOS, the DeviceStorage API allows to scan the device for ZIM files, list them, and let the user choose one from the list. The selected file is then stored in a cookie, to be able to use the same ZIM file on next restart (but the user can still choose another one)
- on all other platforms, the user needs to manually select the ZIM file(s) through the input type=file

Currently, the code tests if the DeviceStorage API exists (https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L406), to choose between these 2 ways.

Historically, there also was a Cordova/Phonegap port (unfinished) that exposed the same capabilities as the DeviceStorage API. The purpose of abstractFilesystemAccess was an abstraction layer between the FirefoxOS and Cordova implementations, and app.js.

My first idea would be to re-enable Cordova on kiwix-js, and use it to generate the UWP application.
It would probably be the best way to have as much common code as possible. Because Cordova already does the job to expose generic APIs, that are implemented differently on each supported platform. And it would probably allow for easy ports on other platforms, and give access to other native APIs.
At first sight, it would be my recommendation.

But I understand it would be a major change in the way to produce the UWP.
If I understand correctly, using "Future Access List" would not allow to search for ZIM files, but would simplify the file selection, and allow to "remember" and re-open the last open ZIM files (this would already be great).
If you want to use that instead of Cordova, abstractFilesystemAccess is not the right place to do it. We'll need to invent another abstraction layer, but it's difficult for me to say how, as I don't know exactly how it would work.

**Comment by Jaifroid** [comment]
OK, thanks for the explanation. Cordova does support W10M (I understand), but unfortunately for me, I don't know how to make a UWP app with that platform and the day job will probably preclude me from learning it in the near future. I think pragmatically, then, I'll have to go with providing a separate layer (equivalent of abstractFilesystemAccess) for UWP and swap it in in the kiwix-js-windows repo only. This will be simplest for me to do.

To clarify, I can't use cookies with a UWP app to store the "remembered" values, afaik (I will double check, but it doesn't seem to work so far despite some tinkering), so Future Access List is probably the only viable short-term solution as it provides the same functionality natively. While I *could* declare a capability for the UWP app to access files and folders in the Documents folder without picking them explicitly (and hence the scanning ability that you mention from FFOS), that would require the app going under much more extensive scrutiny by Microsoft (it doesn't like apps using that capability). The closest we can get to it is allowing the user to pick the folder where the ZIM file(s) are located. Once the user has picked the folder, the app has full read access to the folder and that access can be "stored" and re-used via the "Future Access List". So it is equivalent to the FFOS capability, but has to be done through UWP-specific API (in JavaScript).

I think you're right that an Open Source abstraction system like Cordova is the "way to go", even if in the end it uses the same underlying API's for the OS in question. But for now, I'll develop this as a separate UWP-specific script on kiwix-js-windows. Thank you for your advice.

**Comment by mossroy** [comment]
All right, I understand.
