### ISSUE TITLE
Provide explicit statement about browser or browser engine support

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#271]
The only explicit statement of support currently is "Firefox OS as the primary target". I realize this is a legacy statement, but it may be time to expand the explicit target since the app works on a wider range of systems. I guess we could state support for engines (e.g. Webkit) rather than specific browsers. But it might be worth establishing a list of browsers we will explicitly test each build against.

Possible explicit support targets:
* Firefox (minimum version?)
* Chrome (minimum version?)
* Edge
* Internet Explorer 11 (I can test in this, but don't have earlier versions)
* Safari (desktop if anyone can test it, but not mobile because that is supported by separate app)
* Firefox OS

Not supported or only accidentally supported:
* Internet Explorer in Windows Phone 7.x and 8.x
* Symbian (it's a very old WebKit)
* Opera?
* Blackberry? (but it's Android-based now, no?)

**Comment by mossroy** [comment]
This legacy statement needs to be removed.
For now, the main targets are browsers extensions for Firefox and Chrome.
We need to be careful on what we say we explicitly support, because it means we test it on every release, and provide packages or directions to install it. It also means we need to be extra careful about compatibility when we introduce a new technology.

But we might give 2 different levels of support : 
- the officially supported targets (for which we should give a minimum version, that's right) : Firefox>=45, Chrome>=?, FirefoxOS>=1.2
- the targets that are "reported to work" or even "should work", but not officially main targets : Edge>=?, IE>=11, and maybe other ones (depending on people testing)

**Comment by Jaifroid** [comment]
OK, sounds good. We could add that mainline support for Edge is provided at kiwix-js-windows. As it's fundamentally your repo, @mossroy, and any such statement implies a commitment, it might be better if you edited the wording in the first instance. I'll reassign this to you.
