### ISSUE TITLE
feedNodeWithBlob function in uiUtil.js should use "oneTimeOnly" parameter

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#284]
This will use the native api in the browser for freeing memory after dereferencing the BLOB, rather than a slow jQuery call which has to be attached to a listener. It's also more universal and works with `<link href="blob:...">` elements (these can't be dereferenced with revokeObjectURL because they get dereferenced before the first paint and cause an error). Tested and working in Firefox, Edge, Internet Explorer, Edge Mobile. Needs testing in Chrome and FFOS. Will do a PR if it seems like a good idea. Code to be amended (insertion indicated with asterisks):
```
    function feedNodeWithBlob(jQueryNode, nodeAttribute, content, mimeType) {
        //var blob = new Blob([content], { type: mimeType });
        var blob = new Blob([content], { type: mimeType }, **{oneTimeOnly: true}**);
        var url = URL.createObjectURL(blob);
        /*jQueryNode.on('load', function () {
            URL.revokeObjectURL(url);
        });*/
        jQueryNode.attr(nodeAttribute, url);
    }
```

**Comment by sharun-s** [comment]
@Jaifroid why was that onload handler + revokeObjectURL there? Sometime back, I tried commenting it out and hoping the blob url would stay alive, but I couldn't access it. 
So it hasn't been clear to me what that code did.

**Comment by Jaifroid** [comment]
I think the idea is that, since each blob is created in the browser's memory space, if you have a lot of blobs they'll consume too much memory (significant particularly for mobile browsers). So it is good practice to revoke the object as soon as it is dereferenced. I tried imitating this code for `<link href="blob:...">`, but destroying the blob via the "onload" listener causes the app to crash because the stylesheet hasn't finished painting the page. That's when I discovered that all browsers are required to support a native API for destroying the blob, so I suggest we use that and avoid the overhead of a jQuery call for each blob when it is dereferenced.

**Comment by mossroy** [comment]
This looked like a good idea to use a standard feature instead of re-implementing it by hand, but it seems more complicated. This "onetimeonly" parameter does not seem to work on all browsers.
It is clearly in Microsoft spec : https://msdn.microsoft.com/en-us/library/hh972897(v=vs.85).aspx (but it should be a parameter of createObjectURL, not of Blob constructor)
But it does not seem to be in W3C spec https://www.w3.org/TR/FileAPI, nor in Mozilla spec https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL
Based on https://github.com/BabylonJS/Babylon.js/blob/master/src/Tools/babylon.database.ts#L254 , it might not be supported on Chrome, which raises an error if this parameter is set. I did not test, though.
I find it difficult to find precise information on that topic. Some also mention an "autorevoke" property instead of "onetimeonly"

**Comment by Jaifroid** [comment]
OK, thanks for the info. @mossroy . I'll test with Chrome to see if it flags errors. I thought I read somewhere that all browsers had to obey this. Needs further research.

**Comment by Jaifroid** [comment]
This feature was never fully implemented in all browsers, so we cannot rely on it. I'm closing this issue.
