### ISSUE TITLE
Use Apache Cordova to generate apps for different platforms while using some native APIs

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#287]
Kiwix-js has been used to create apps for Windows 10 mobile (see https://github.com/kiwix/kiwix-js-windows), and recently for Ubuntu Touch (see #285).

It seems to work quite well in pure HTML/javascript.
But it's very tempting to use some native APIs to enhance the user experience. In particular to read the ZIM file without having the user manually select it each time the app is launched.

Cordova exposes some native APIs through javascript, making it possible to have a single javascript codebase that works on many platforms.
Windows 10 mobile and Ubuntu Touch are among the supported platforms : https://cordova.apache.org/docs/en/latest/guide/support/index.html

In our case, the File API might do what we want : http://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html (but this needs to be tested)

**Comment by Jaifroid** [comment]
I agree this would be good. Currently, in trying to adapt the code to use UWP storage and access the remembered folders, I am having a hard time identifying an entry point that doesn't disrupt existing code too much. The FFOS storage format seems to be "hard coded" and assumed if I try to pass an array of directories to the app, and then it bugs out because the array doesn't have the properties expected.  The UWP storage object seems to have a very different structure. I can't inject the directory or files into the input form/file picker, because of the security model..

I think a lot of the FFOS code needs to be fully hived off into a separate module, so that we could have a plugin structure to support different OS's and fully abstracted code in the app itself. Cordova might be one way to achieve this, though I don't know if it supports FFOS. I'm currently faced with having to comment out a whole load of subroutines just to get past the tests that the code does once it assumes FFOS storage (and which don't work with other storage devices).

**Comment by mossroy** [comment]
When we removed the Cordova code in version 2.1, we removed some abstraction layer too. For example https://github.com/kiwix/kiwix-js/blob/2.0.0/www/js/lib/osabstraction.js
If we want to use Cordova, we should resurrect some of this code. But maybe it's not enough.
The Cordova API we need https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html says it supports Firefox OS, but it's not using the right API so would be useless for us (it simulates a filesystem on top of indexedDB, instead of using the DeviceStorage API).

In any case, don't spend too much time trying to keep FFOS compatibility if it gets complicated. If you want to try Cordova, try to make it work, and then we'll see what we do regarding FFOS.

**Comment by kelson42** [comment]
@mossroy @Jaifroid Shoukd we keep this ticket open? It seems that Jaifroid has followed, with success, the same goal but with other frameworks.

**Comment by Jaifroid** [comment]
I agree. Apache Cordova is now superseded by more modern frameworks. It's still alive, but there are so many options now such as React JS, Ionic, the growning OS support for PWAs (a more elegant solution than using a framework IMHO), and of course the ubiquitous Electron for all desktop OSs. I don't see us ever advancing this issue. I'm closing, but of course re-open if I've closed prematurely.
