### ISSUE TITLE
Do we really need the hamburger menu?

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#293]
@mossroy @sharun-s , could we have a quick discussion over whether the hamburger menu in kiwix-js is fit for purpose? These are my initial thoughts:

- There's no need for it, because we only have three pages, and all three menu items easily fit on even the narrowest of screens;

- It reduces discoverability and hinders navigation -- when you go to configuration and change an option, there is no obvious way of getting back to the home page without opening the hamburger -- user feels "lost" at first;

- It requires an annoying extra click to move between app pages -- so, to go into config, change an option, and return, requires five clicks (Hamburger, Config, option, Hamburger, Home) as opposed to just three (Config, option, Home), plus user has to hit a small button each time;

- (Related side issue): On mobile, there's no need to reduce the size of the top nav bar quite so much because it scrolls off the screen when reading a page, at least it does on Windows Mobile -- reducing it makes the buttons a bit difficult to hit on a small screen.

Below is a screenshot of what it would look like without the hamburger (it's easy to remove). As I say in my final issue, I think the bar is a bit narrow and could keep its initial size on mobile, since it scrolls off the screen. Note that it is just as narrow with the hamburger, and the hamburger button is an even smaller target to hit.

![image](https://user-images.githubusercontent.com/4304337/28559752-d0878946-710f-11e7-9760-0432f71031a7.png)

**Comment by mossroy** [comment]
A few things to keep in mind :
On small devices (like the ones I have with Firefox OS), the screen size seems a bit too small to have all the menu names. Example (from the Firefox OS Simulator, with Mozilla Flame screen size : 320x570) : 
![image](https://user-images.githubusercontent.com/890923/28570678-7dd78676-713f-11e7-86bf-ea225daea379.png)
And hopefully one day we might translate the UI in some other languages, where the menu names might longer.
Regarding the menu height, it needs to be small because, on some small devices (like the ZTE Open C), when you use the search form, it displays the on-screen keyboard that eats a lot of space. If the menu is too big, you wouldn't even see the search results. See example (with the ZTE Open C screen size : 320x450) : 
![image](https://user-images.githubusercontent.com/890923/28570786-00966ab4-7140-11e7-8fb4-27b82efd6697.png)

But I'm not against some tweaks on this menu behavior. And I agree with you that going back from Settings to Home can be improved in terms of usability.
The responsive design is brought by Bootstrap, which decides to display the hamburger menu or not, based on the available screen size. I find it very convenient to have these aspects handled by a library instead of having us do the job. But the size thresholds can certainly be modified.

**Comment by Jaifroid** [comment]
Thanks, @mossroy , I didn't realize there were such small screens nowadays! But good to know. Maybe we can think about reducing the size at which the hamburger flips in. It's the @media screen declaration in the CSS. I've become quite annoyed by this hamburger on my phone, due to switching back and forth so much during testing... I'll experiment a bit with different viewport sizes (but it's not high priority).

**Comment by sharun-s** [comment]
Just an fyi - the recent Chrome devtools update comes with a nice code coverage tab and so I naturally ran it on Paris.html. You can see whats at the top. Red indicates unused code. 
![pariscodecoverage](https://user-images.githubusercontent.com/18413274/28603575-afb8cd46-71e2-11e7-895b-4fbcbc722a79.PNG)

If you run an "Audit" you can find all the css rules that can be junked. 
![screenshot 1](https://user-images.githubusercontent.com/18413274/28603651-07ea9daa-71e3-11e7-8bde-690e6ee15764.png)

**Comment by Jaifroid** [comment]
I think this issue can be closed. It would be superseded by #523 .
