### ISSUE TITLE
"Take our website with you"

### ISSUE THREAD

**Issue by Stamimail** [kiwix/kiwix-js#307]
@Mossroy
Sorry for not having programming knowledge...
Although,
If there is no good solution to have the offline wikipedia in browser like the online wikipedia, perhaps it is the time to make a new technology. It seems it is Mozilla job.
Currently a user that wants to download a website uses HTTrack or wget etc.
But here we are talking about websites (not only wikipedia) that want to let the user take their website with him, for offline use.
The browser should think it is connected to far server but really is connected to a file on the local system.
Other extensions of Firfox like "Thumbnail Zoom Plus" (For image and img links zooming) also should work, when this ZIM (Website File) is loadead to browser.
This Website File could contains Whole website or parts of it, like a book in Wikisource.

**Comment by kelson42** [comment]
Wanting to offline an random web site is a legitimate feature request. That said, having this working on a normal internet connection seems a bad idea - because for many reasons things might go wrong. I strongly recommend that if this is at some point implememented, this relies on a web service (zimit for example) hosted on an external with better resources (bandwith, CPU, ...).

**Comment by Stamimail** [comment]
> having this working on a normal internet connection seems a bad idea
What do you mean? After downloading a website for offline use, the offline website won't be needed an internet connection to work?

**Comment by kelson42** [comment]
@Stamimail Scrapers won't work always properly on user connection to Internet.

**Comment by Jaifroid** [comment]
Some interesting information on the Progressive Web App front and Service Worker support in Edge / Windows 10 more generally:

https://blogs.windows.com/msedgedev/2018/02/06/welcoming-progressive-web-apps-edge-windows-10/ 

Obviously this is Microsoft catching up, but it's interesting that they're placing PWAs at the core of their app strategy. Kiwix JS isn't technically a PWA because it works primarily offline rather than following the PWA concept of primarily working online with offline content as a fallback for when there's no connection. But there's clearly quite a lot of overlap, since the "online" aspect of Kiwix could simply be downloading the ZIM, which then works offline until it's time to update it.

I think what's quite exciting here is the idea that Kiwix JS could be a PWA on the Kiwix servers, without needing a Store, but that it would still be a "first-class" app experience for the user, not perceived merely as a pinned Web page. And of course it's not tied to Windows, but could be truly cross-platform, OS-agnostic depending on how well embedded PWAs are in the specific OS.

**Comment by kelson42** [comment]
A classical web app or mobile app fully relies on the connection to Internet. We have exactly the opposite approach. Both approaches are lacking of a smooth transition from the one to the other (offline <-> online).

That's why I think we will have to be more and more "progressive" if we want to improve our UX (but just from the opposite direction like what is meant traditionally with "progressive").

That said, the exact full solution we will implement is still unclear to me as we are still quite busy with full offline proper support. WORK IN PROGRESS :)

We should probably close that ticket as this is primary an openZIM topic (format/scrapper/web service). The whole thing is an EPIC anyway.

**Comment by kelson42** [comment]
@Jaifroid @mossroy Even if interesting, I don't think this ticket belongs to this repo.

**Comment by Jaifroid** [comment]
@kelson42 I agree. Can you move it or close it as you see fit?

**Comment by Stamimail** [comment]
>Should probably be advantageously moved to https://github.com/openzim/zimit.
How to? Do you need me?

**Comment by Stamimail** [comment]
>Should probably be advantageously moved to https://github.com/openzim/zimit.


How to? Do you need me?

**Comment by kelson42** [comment]
We will implement Zimit in 2020, see https://twitter.com/KiwixOffline/status/1202942929758806017.
