### ISSUE TITLE
Make vCard geo: and tel: URIs work

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#313]
Wikivoyage ZIMs use URIs of type:

`geo:37.04741,22.11429`

and

`tel:+302721023999`

These are part of the vCard schema, see in particular: https://en.wikipedia.org/wiki/Geo_URI_scheme . They are currently not handled in jQuery mode at least. It's quite easy to make them into links that will be handled by whatever the underlying Operating System (or browser) has registered to handle such links. For example, on MS systems or in Edge the "tel:" URI opens a dialogue box asking the user if they want to launch Skype or whatever other apps are registered to handle "tel:" URIs.

I can do a PR for this.

**Comment by mossroy** [comment]
I agree.
It's probably only a matter of letting these URIs as they are : the jQuery mode certainly wrongly thinks it's a URL it should retrieve from the ZIM.
If the URI is untouched, the browser/OS will try to handle the link appropriately.

I don't know it there is a more generic way to recognize this kind of link than looking for "tel:" or "geo:" prefix.
Ideally, we would have a generic way to recognize the URI scheme, and ignore all but the links in the ZIM content.
For example, the "mailto", "ftp", "irc" schemes should be ignored too.

If necessary, we can use the complete url (given by "this.href") instead of the raw href string (given by $(this).attr("href"))

**Comment by Jaifroid** [comment]
The basic and easy way to support geo: and tel: would be like in commit https://github.com/kiwix/kiwix-js/commit/a16be0e1bc93ac33813d002184045eb6a2bbc13c .

Adding the href target means that the user doesn't navigate away from the Kiwix app (which is not a great thing to happen when reloading it involves picking the ZIM file again).

A generic approach I guess would involve recognizing *only* links that should be opened from the ZIM and leaving all others alone. Is there enough to identify a ZIM link other than by elimination of those that are obviously not in the ZIM?
