### ISSUE TITLE
running on raspberry pi hardware with display

### ISSUE THREAD

**Issue by thearkadia** [kiwix/kiwix-js#357]
we're working on portable computer project and want to use kiwix for wiki and stackexchange. Running it as an extension on chromium isn't the most efficient on a pi. Is there a better way to run it so we can run it as a native application? here's the project we're running it on https://github.com/thearkadia/The_Ark/blob/master/README.md 
![img_1354](https://user-images.githubusercontent.com/6326785/38827685-b4086d88-4181-11e8-8c4f-6b8353581cb0.jpg)

**Comment by thearkadia** [comment]
It’s running raspbian. The device uses the same chips as the raspberry pi

**Comment by Jaifroid** [comment]
OK, so then it looks like the GNU/Linux executable linked from the front page of kiwix.org might run natively on Raspbian (I don't have any experience with it, but it is a GNU/Linux variant, no'). At least try the executable for testing, and it should be considerably faster than running Kiwix JS in Chrome. If it works, then you can consider tinkering with the source code and recompiling to fit your project.

**Comment by mossroy** [comment]
Interesting project. I ping @kelson42 so that he has a look a it.
Before compiling kiwix, you might try the nightly builds of https://download.kiwix.org/nightly/ . For example, https://download.kiwix.org/nightly/2018-04-16/kiwix-tools_armhf-2018-04-16.tar.gz should run on it. If you run kiwix-serve in the background, it will run a local webserver that you can access from a browser.
If it suits your needs, it will indeed be faster and more feature-complete than kiwix-js.

If you need to stick with kiwix-js, it can run from a local copy of the sources (just point your browser to the index.html file).
In the screenshot, the screen size does not seem to fit inside the actual screen (some missing parts on the right) : maybe this should be fixed to be able to read all the content.
I see that you were browsing a stackexchange ZIM file : please note that some fixes have been implemented recently for that kind of ZIM files, that are merged in the master branch of this project, but not released yet (it will be in 2.3)

**Comment by kelson42** [comment]
I would recommend to kiwix-serve for ARM (in kiwix-tools release):
https://download.kiwix.org/release/kiwix-tools/

You can easily have an HTTP daemon providing the ZIM content and then you can connect to localhost.

@thearkadia Is that a desktop or server solution running on your RPI?

**Comment by thearkadia** [comment]
its a desktop solution

**Comment by kelson42** [comment]
I have open a ticket to provide binaries for RPI of future Kiwix-desktop 2.0:
https://github.com/kiwix/kiwix-build/issues/153

Otherwise, it seems to me we can not do more for that ticket!?

**Comment by thearkadia** [comment]
@kelson42 awesome, thanks! <3

**Comment by mossroy** [comment]
So I close this issue for now
