### ISSUE TITLE
Ubuntu touch Migration

### ISSUE THREAD

**Issue by ernesst** [kiwix/kiwix-js#375]
@mossroy, the developper of Ubports are migrating our phones to 16.04 LTS version... for an obvious reason, the 15.04 will not be supported then. They are targeting the change within 2 months.

The main changes, pretty simple, are mentioned there : https://forums.ubports.com/topic/1215/updating-apps-to-16-04/13
On the store side, there is the possibility to upload both OS version. 

I don't remember how I compiled initially your work, i've failed to use cordova for 16.04, hopefully Kiwix doesn't use it.

**Comment by Jaifroid** [comment]
@ernesst , Kiwix JS does not use Cordova. Also, as it is a JavaScript app, it shouldn't need to be compiled as the code is interpreted by the OS's browser engine in the app framework, not compiled to native. It may just be a question of changing the manifrest and the .apparmor file, updating the html and JavaScript files to  the latest Kiwix version, and then packaging the app with whatever packaging mechanism Ubuntu touch uses.

**Comment by mossroy** [comment]
@ernesst : I'm not clear on the migration path.
I suppose the phones on 16.04 will still be able to run apps compiled for 15.04?
In this case, I suppose we can keep a 15.04 app more than these 2 months?

I'd like to avoid maintaining 2 versions of the app. If it's not too complicated, we might (for example) say that v2.3 wouldbe the last version compiled on 15.04 (and we would keep it on the store for a long time, for non-upgraded phones), and switch to 16.04 for v2.4 (but it will clearly be later than 2 months).
In this case, phones on 15.04 would need to upgrade to 16.04 in order to have v2.4.

Keep in mind that kiwix-js is pure javascript/HTML, so I suppose it should work the same on 15.04 or 16.04.
Building the app is now done automatically by Travis, but it also can be run manually for testing/debugging. See https://github.com/kiwix/kiwix-js/blob/master/.travis.yml that runs https://github.com/kiwix/kiwix-js/blob/master/scripts/package_ubuntu_touch_app.sh , based on config files in https://github.com/kiwix/kiwix-js/tree/master/ubuntu_touch

**Comment by mossroy** [comment]
Based on the stats on open-store.io , the vivid version is not downloaded any more since v2.3.1 of kiwix-js : 
Revision | Channel | Version | Downloads
6 | Xenial | v2.3.1 | 32
7 | Vivid | v2.3.1 | 0
8 | Xenial | v2.4.0 | 111
9 | Vivid | v2.4.0 | 0

So I suppose it's now safe to switch to xenial, and drop vivid support

**Comment by mossroy** [comment]
This should have been fixed by #476
