### ISSUE TITLE
Add support of ZIM meta information reading

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#395]
We need to easily achieve to get the value of these metadata:
http://www.openzim.org/wiki/Metadata

This is necessary to apply a proper voice filtering (based on ZIM content language) after @kasemmarifet has implemented the TTS system.

**Comment by Jaifroid** [comment]
We currently have access to the filename of the ZIM, if the user hasn't renamed it. Are all ZIMs obtained from Kiwix guaranteed to have a language code in the filename? In Kiwix JS Windows, I currently use the language code as a filter to find ZIM archives by language in the ZIM file download system. I realize that reading the metadata is the proper way to do it... but sometimes a shortcut can prevent roadblocks...

**Comment by mossroy** [comment]
I've created PR #397 that should implement that.
@kasemmarifet : please test that it suits your needs.
NB : the language read inside the ZIM file is in ISO-639-3 format, where the SpeechSynthesis API uses the BCP 47 format (see https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/lang).
In theory, there would be a need to convert between these formats, even if they seem to usually have the same value (based on a few random tests in https://iso639-3.sil.org/code_tables/639/data)

**Comment by Jaifroid** [comment]
Note that on testing a Spanish-language Wikivoyage with the current PR #397, the M/Language value returned form the ZIM is "spa". Unfortunately this is not the same as the BCP 47 format which should be es-XXX -- "spa" is not a valid tag in that schema, see http://schneegans.de/lv/?tags=spa&format=text . @kelson42 is there another value we should be reading to return "es" from the ZIM? As mentioned above, the archive filename has the BCP47 language code, but it's preferable if there is one inside the ZIM.

**Comment by Jaifroid** [comment]
We could introduce a translation table, but if you take a look at the list of language codes I implemented for the languages download filter in Kiwix JS Windows here: https://github.com/kiwix/kiwix-js-windows/blob/master/www/js/lib/kiwixServe.js#L22 , you'll see that there are a lot of potential codes to translate between.

It occurs to me that we could extract the two-letter code in the metadata key M/Name, which should look something like this: kiwix.wikipedia_en.nopics (according to the spec). I need to investigate, unless @kelson42 can tell us, whether this name always contains the two-letter language code following an underscore. If it is always the case at least for current ZIMs, then it could be an alternative to implementing a large translation table.

**Comment by kelson42** [comment]
@Jaifroid language code have usually 3 letters, see http://www.openzim.org/wiki/Metadata
@mossroy I think this should be in a manner to access easily *all metadata*, would bit a bit sad to implement all of this only for the "language" metadata.

**Comment by Jaifroid** [comment]
@kelson42 BCP47 is the specification we need to determine which text-to-speech synthesis language to use. BCP47 language codes are of the following type:

en - English
de-AT - German as used in Austria
es-419 - Spanish as used in Central and South America

The difference here is, for example, that the M/Language code returned from the ZIM is "spa", whereas the code we need to select the correct language for synthesis is "es". "es" is the two-letter code used in the name of the ZIM, e.g. `kiwix.wikipedia_es.nopics`. This is why I'm suggesting we might use that two-letter value (es).

**Comment by Jaifroid** [comment]
Further info: The definitive subtag registry is here: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry . It defines language subtags, such as `fr` for français, and also region subtags such as `CH` for Switzerland. This can give us combinations such as `de-CH`, but I don't think Wikipedia breaks down languages usually to regional level. There is no specific Colombian Wikipedia (`es-CO`). However, there is a specific Tunisian ZIM extracted from the French Wikipedia, which is `wikipedia_fr_tunisie_...`. The underlying Wikipedia is still nevertheless the main French Wikipedia, so `fr` is the language code required to select the correct language for text-to-speech synthesis. We should probably just match the first installed voice that has the base language code. For example, if someone has the `es-MX` (Mexican Spanish) voice installed, we should use it to read Spanish language ZIMs. If they have both Castilian Spanish and Mexican Spanish voices installed, we should use the system default if it matches, or the first voice that matches the language code in the list.

(Including @kasemmarifet so that they are aware of this discussion.)

**Comment by mossroy** [comment]
Regarding reading other metadata : it's true that I should provide a generic API for that. I'll try to refactor for that.
But I don't think we should read all this metadata when the ZIM file is selected. Because each metadata entry is a separate "article", that needs many file access to be read, and might need to be decompressed. Our current code is less optimized than libzim, so it might become slow.
I would suggest to provide a generic API, but use it only when needed.

**Comment by kelson42** [comment]
@Jaifroid We won't change the openZIM standard for language code. A conversion needs to happen here.

**Comment by Jaifroid** [comment]
@kelson42 OK, thanks. I wasn't suggesting the standard should change, just asking whether the language code embedded in M/Name , which does appear to be BCP 47, is something we can rely on. I haven't yet found any ZIM archives with unreliable language codes in the name, with the exception of an old Stackoverflow ZIM  which is entitled `stackoverflow.com_eng_all`. All the others seem to use _en, _es, _de, _ar, _zh, etc. It would be nice to avoid having to add a whole package if the code is already available to us.

**Comment by kelson42** [comment]
@Jaifroid You can not rely on ```M/Name``` for the language. Rely only on ```M/Language```

**Comment by Jaifroid** [comment]
Thanks @kelson42 -- do you have plans to change the naming scheme for ZIM files? The problem with M/Language is that it is in an unusable format for us, and although you say we cannot rely on M/Name, pragmatically, every ZIM except one that I have been able to find has the correct code embedded in the file name. If we cannot **rely** on the code, is there a reason why we cannot pragmatically use it until the format changes? It would be *so much* simpler than trying to implement conversion!

**Comment by kelson42** [comment]
@Jaifroid I offer no guaranty regarding the filename. M/Language is what is used by all Kiwix ports, so I wonder why this is not usable for Kiwix JS? Conversion should not be a problem.
