### ISSUE TITLE
In jQuery mode, inject noscript tags

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#433]
We currently do not support javascript in jQuery mode.
ZIM files generated by mwoffliner in early 2018 rely on javascript to open the sections. That's why we had to implement a dirty workaround : https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L960 (see #355).
This has been very recently fixed in mwoffliner : https://github.com/openzim/mwoffliner/issues/324
So future ZIM files generated by mwoffliner should be able to work on kiwix-js in jQuery mode with a more generic and reliable fix, as there is now a `<noscript>` tag in the HTML that opens the sections.

So we should add some code that inject the content of `<noscript>` tags (if any).
A simple way to do that would be to remove these tags in the HTML before injecting it in the iframe. But we need to check if there's a risk to remove actual content (like in a https://developer.mozilla.org/en-US/docs/Web/API/CDATASection content).
Another way to do it is to inject the content while parsing the DOM. It would allow a safe detection of these tags. In theory, it would slow down the content display (and imply some redraw), but we already wait for the CSS to be injected before actually displaying, so it should not add some redraw.

Should we keep the dirty workaround? I unfortunately think so, in order to be still compatible with the ZIM files generated in 2018.
But we should disable it when testing with noscript, and add some comments to explain why we still keep it (it will look redundant)

**Comment by Jaifroid** [comment]
CDATA is X(HT)ML only, so unlikely to be in the ZIMs, no? But I guess that's just an example. We could simply inject the style into the header, and it could trivially be done with a regex before DOM injection, or through DOM manipulation afterwards. Another simple solution is (was - I haven't checked if it still works) to remove the class "client-js" that has been added to the HTML by mwoffliner, and is not present on Wikipedia.

Whatever method, I don't think it will have much of a performance effect, so long as we do it before first paint, as you say.

**Comment by Jaifroid** [comment]
A regex solution:
```
var noscriptContents = /<noscript>\s*((?:[^>]|>(?!\s*<\/noscript>))+>)/.exec(document);
if (noscriptContents[1]) {
    document=document.replace(/(</head>)/i, noscriptContents[1] + '$1');
}
```
But as you say, it wouldn't work for older-style ZIMs. We could cheat by injecting the style rule without extracting it from the noscript section, since we know what it is. It's probably a less dirty workaround than our current one of iterating over all sections and opening them programmatically.

**Comment by Jaifroid** [comment]
OK, I've tested, and the simplest solution is to remove `style="client-js"` before injection as it has exactly the same effect. Since `client-js` is added my mwoffliner specifically as a workaround to enable opening-closing of sections (because the supplied script from Wikimedia "doesn't work"), removing it disables the mwoffliner workaround rather neatly.

It can be done with:
```
    // Remove client-js syle from html to ensure all sections are open if we don't support JS in the ZIM
    htmlArticle = htmlArticle.replace(/(<html[^>]+?)\s+class\s*=\s*["']\s*client-js\s*["']/i, '$1');
```
Above regex could be simplified. It has redundancy in case of whitespace having been added.

**Comment by mossroy** [comment]
Keep in mind that this needs to be a generic solution (i.e it does not make any assumption on the HTML structure or origin). It should enable the content of noscript tag(s) on a random ZIM file (even not generated by mwoffliner). So I don't think we should play with client-js (or anything specific to mwoffliner).
Your first regex solution probably works (I did not check either). But I would not have moved the code in <head> section. I suppose a browser with javascript disabled would interpret the content where the <notag> is : let's do the same.

Yes, CDATA was an example, I'm not sure if there are other technical possibilities of unescaped tags in an HTML string, that would not be interpreted as HTML tags.
It's probably possible to check that the <noscript> tag is not inside a CDATA, but I don't know if it's worth making the code complicated (I don't know if we can take the risk of not handling it).

As I said in the description, a completely different implementation would be to handle that in the DOM, after injecting the (untouched) HTML string. In function displayArticleContentInIframe, we would use jQuery (or built-in DOM parsing) to find <noscript> tags, and replace them with their content.
It would be safer (no risk to match a <notag> string that would not be an HTML tag), probably not very complicated, even if maybe a bit slower.
On the other hand, the injection would occur later. If the content was javascript, it could be a problem. But obviously it will not be (putting some javascript inside a noscript tag would be a misunderstanding of the purpose of that tag...). It's probably not a problem for CSS content, or for HTML content? I'm not 100% sure.

As you can see, I don't yet have a strong opinion on which implementation is the best : any thoughts?

**Comment by Jaifroid** [comment]
There is one other alternative: enable JavaScript in the ZIM in jQuery mode. I have updated the JavaScript Support branch so it works now with the new-style ZIMs. It also "almost" works with PhET ZIMs in that it is possible to load and run simulations using the random button. However the very first (landing) page is unresponsive for some reason I haven't yet debugged.

Anyway, it seems we'd still need backward-compatibility with ZIMs that launch with all sections closed even in Desktop view. IMHO that's really ugly, so I think we're forced to open the sections. If we want to keep open the possibility of enabling JS in the ZIM in jQuery mode (and I would like to keep that possibility, since it's nearly there!), we can't use the noscript solution, because it could break any random ZIM that uses JavaScript (if we're supporting JavaScript).

So it leaves us with either keeping our current workaround, or injecting a style rule ourselves into the header. I think the style rule solution is neater *if it works*. Neither solution is generic, but then we're not actually treating a generic problem are we? We're treating a specific problem with legacy Wikimedia ZIMs,, and that specific problem is probably best treated with a specific remedy that targets only the issue, with no danger of impacting on anything else. What do you think?

**Comment by Jaifroid** [comment]
I've tested out a solution for the opening-closing issue with this commit: https://github.com/kiwix/kiwix-js/commit/0247219f8807c52254fd71bbbb0a7b73b6f0e98c . If you follow the link, you'll see the code. The effect can also be tested by running the [JavaScript Support](https://github.com/kiwix/kiwix-js/commits/javaScript-support) branch (with a legacy ZIM).

Because of the `@media all and (min-width: 720px)` condition, it only opens headings in Desktop views (i.e. widescreen), while in mobile views (narrow screen) the headings are closed. But this branch is backwardly compatible with the opening-closing algorithm in legacy ZIMs.

If we want a solution without supporting JavaScript, we simply remove the condition, forcing all headings open in all views.

Just from the perspective of the code, and without implying we should enable JS support, what do you think of doing it this way?  

(The solution works also with the new-style ZIM fragment we were given for testing, but there's a slight wrinkle I need to debug with the JS in that ZIM -- it works, but top-level heading gets programmatically closed.)

**Comment by mossroy** [comment]
The idea here was to make a first step : handle the `noscript` tags in jQuery mode, in a generic way. So that it would work not only on ZIM files generated by mwoffliner.

If afterwards javascript is enabled in jQuery mode, we would remove (in our code) this handling of `noscript` tags, and replace it by the code that enables javascript.
This is what browsers do : if javascript is disabled, handle the `noscript` tag; if javascript is enabled, ignore the `noscript` tag.

Now, there is the issue of ZIM files generated by mwoffline in early 2018. If we remove our current workaround, they will not work. So I would suggest to leave our current workaround (and add some comments on why it is still there), even if we handle the `noscript` tag too : we only have to check that both play well together (I think it should be the case)

**Comment by Jaifroid** [comment]
OK, let's wait to see what happens in the end with https://github.com/openzim/mwoffliner/issues/324 , as it's in flux. In any case, I agree we can try to handle the `noscript` block, but when we add JS support in jQuery mode, we should have an option in the interface: `Enable JavaScript in the ZIM? (experimental and uses more memory)`. Then it would either process or not process the `noscript` block based on the setting.

I'm thinking of this as a jQuery mode option, but in principle it would be good to give users the option to turn off (or on) JS in SW mode too, because it is resource intensive and slows down page-load times needlessly for the most common use-case for Kiwix JS (as a portable encyclopaedia/dictionary).
