### ISSUE TITLE
Chrome can not seek inside videos in ServiceWorker mode

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#452]
At least on TED ZIM files.
When you click on a position in the video, it restarts the video from the beginning, instead of jumping to that position.

It works fine on Firefox (both in jQuery and SW modes). It also works fine on Chrome in jQuery mode.

**Comment by Jaifroid** [comment]
I've tested this in Edge. With webm videos (in SW mode) Edge cannot jump to a specific point in the video either. However, with mp4 videos (such as those in the TEDx Global Issues ZIM), Edge can jump forward.

However, in jQuery mode, Edge can jump around without problem in a webm video. So I wonder if the issue is to do with the video.js plugin that is used in these ZIMs (and which doesn't run in jQuery mode).

There seem to be other issues: subtitles cannot be selected in SW mode (at least in Edge), whereas they can be selected in jQuery mode. Again, I suspect the video.js plugin is at fault, but it's just a guess.

**Comment by mossroy** [comment]
Thanks for your tests on Edge.
It might come from some missing headers in the response sent by the ServiceWorker.
The MIME type is not set : this needs to be fixed (both for videos and subtitles), but adding it does not seem to be enough.
Maybe we also need to add content-length and/or content-range.
I'll try to test.

**Comment by Jaifroid** [comment]
I've tried reverting (for testing purposes) the JavaScript support in SW mode. Without JS, the video.js doesn't load. In Edge, unfortunately this still doesn't allow seeking in a webm video. It does allow the subtitle (CC) menu to show (whereas with video.js it doesn't even show). However, the actual subtitle files can't be found when I try to select one, and I get the errors shown below (I realize this is a different issue, but might uncover another possible problem, so I mention it).

![image](https://user-images.githubusercontent.com/4304337/50217708-5e57fd00-0381-11e9-83fe-f7373e39b23e.png)

**Comment by mossroy** [comment]
Please ignore my last comment for now. It might be the same issue
