### ISSUE TITLE
Titles apparently missing in wikivoyage_en_all_novid_2019-04.zim

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#485]
As per https://github.com/openzim/mwoffliner/issues/605 we appear to have an issue with missing titles when `wikivoyage_en_all_novid_2019-04.zim` is viewed in Kiwix JS. I initially thought this was an mwoffliner issue, but it appears it may not be, and that the issue may be with code in Kiwix JS. I open this issue in order to investigate whether the problem is indeed with Kiwix JS.

**Comment by Jaifroid** [comment]
Here is another screenshot to show the issue:

![image](https://user-images.githubusercontent.com/4304337/56377055-5e69eb80-6201-11e9-9cee-cd60584b2097.png)

**Comment by Jaifroid** [comment]
For comparison, here is the dirEntry for "[Lausanne]":
![image](https://user-images.githubusercontent.com/4304337/56441267-71a1b780-62e4-11e9-825d-1cd1919f7f58.png)

And here is the dirEntry for "A Taste of Coastal Texas":
![image](https://user-images.githubusercontent.com/4304337/56441212-3dc69200-62e4-11e9-8e3e-14e5828b944c.png)

As can clearly be seen, the title property of the dirEntry is blank for "[Lausanne]", but not for "A Taste of Coastal Texas".

@ISNIT0 noticed, and I confirm this, that all the one-word titles are missing in Kiwix JS, but all titles with two or more words are present in the corresponding dirEntry.

As @ISNIT0 showed Lausanne appears with a title field when extracted with `zimdump`. However,  `zimdump` uses `libzim` to read the Zim contents, and `libzim` has [this line](https://github.com/openzim/libzim/blob/684c355a6c56208c3d9e0be7990c4923b7ed8c50/src/_dirent.h#L84) which fills in the missing title from the URL when reading the dirEntry.

Therefore, it seems to me, that the most likely scenario is that this ZIM is in fact missing titles for one-word dirEntries. @mossroy , would you concur? Is there any other test we can do to show this?

**Comment by mossroy** [comment]
That's what seems the most probable to me too.
If we want to be 100% sure, we should check that the title is not emptied by our javascript code.
You could put a breakpoint in a more low-level javascript function, like line 142 of zimfile.js, which constructs a dirEntry from the ZIM file.
If you have a breakpoint when reading the dirEntry of a one-word title, you could check in the `data.subarray(pos + 1)` byte array that the title is not there (it should directly start with a byte 0, instead of the title followed by this 0).
As you're reading the actual bytes of the ZIM files (with no code to interpret them), there would be no doubt on the conclusion.

**Comment by Jaifroid** [comment]
Thanks for the pointers, @mossroy .
Here is the result of pausing on line 142 of `zimfile.js` on the dirEntry for "Lava". The URL has been successfully found starting at position 16. The value of `pos` at line 142 is `20`, so the code expects to find the title starting at `pos + 1`, i.e. `21`:

![image](https://user-images.githubusercontent.com/4304337/56454479-e1498e00-6348-11e9-9619-0efd8074ae71.png)

As can be seen, the value at position 21 is `0`, meaning that the title for the dirEntry corresponding to `Lava` is missing, as indicated in Kiwix JS by our square brackets:

![image](https://user-images.githubusercontent.com/4304337/56454496-31c0eb80-6349-11e9-8a25-a5ef980e1b55.png)

@ISNIT0 If you point me to the code on GitHub that inserts the title in mwoffliner, I'd be happy to look over it for any bug that might be omitting the title for one-word entries. The behavour seems very specific!

**Comment by ISNIT0** [comment]
As per https://github.com/openzim/mwoffliner/issues/605#issuecomment-484043808
I think it's quite likely that libzim is refusing to write a title that is the same as the id, because this would be duplicating un-necessarily.

An example of differing title/ids:

articleId | articleTitle | isEqual
 --- | --- | ---
`Lava_Hot_Springs` | `Lava Hot Springs` | `false` |
`Laval` | `Laval` | `true` |

This would explain why you are only "missing" the titles that have no space character (as that's the thing that commonly causes differences) (https://github.com/openzim/mwoffliner/issues/605#issuecomment-484461220)

**Comment by Jaifroid** [comment]
Thank you, @ISNIT0. That makes sense (I hadn't properly understood [that comment](https://github.com/openzim/mwoffliner/issues/605#issuecomment-484461220), because I was on a train at the time!). So the reason we're seeing this behaviour now, and never previously, is because up until the recent format change the URL would have been `Lava.html` and the title `Lava` so mwoffliner would write the title always. Now that the `.html` has been dropped, in may cases the title and the URL are the same, so mwoffliner will only write the latter.

Taking a look at [the spec](https://web.archive.org/web/20190212222559/https://wiki.openzim.org/wiki/ZIM_file_format) (currently offline, so I'm consulting it on archive.org), it defines `title` as "string with a title as refered in the Title pointer list or empty; in case it is empty, the URL is used as title".

@mossroy Given this, should we change our behaviour in app.js [line 711](https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L711), to use transparently the URL if the title is missing?

**Comment by mossroy** [comment]
Yes, we should remove the square brackets when we use the URL instead of an empty title, as it is in fact the normal behavior.

But we could do that in different ways :

1. simply modify line 711 of app.js, to remove the square brackets
2. introduce a function in class DirEntry that does that transparently (called something like getTitleOrUrl), and use this function everywhere instead of the title attribute
3. introduce the same function, but call it getTitle like in libzim

As the use of the URL instead of the title is in [the spec](https://wiki.openzim.org/wiki/ZIM_file_format#Namespaces), it's probably not safe to use option 1, because there might be other places in the code where the fallback to URL would be needed too. IMHO, this fallback should be coded only once, and used everywhere.
Option 3 would make our code work exactly like libzim. It would be convenient, but I find very confusing that a getter does that. See how long it took four people to understand this behavior
That's why I would be in favor of option 2 : we have exactly the same behavior as in libzim, but with a more explicit naming.

**Comment by Jaifroid** [comment]
@mossroy I agree with Option 2. Although in Kiwix JS we only use `dirEntry.title` in one place in `app.js`, in Kiwix JS Windows I use it in five places, so having a getter would help downstream, and I also agree that it would avoid the kind of confusion that this issue has caused as a result of the change of URL format.

I've opened PR #488 to implement.
