### ISSUE TITLE
Wishlist for version 2.7

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#541]
This is to discuss what we would like (and could) do for next version.

Here is my wishlist : 
- @Jaifroid , if you're still interested in doing it, it would be great to improve the UI. By backporting some of the work you did for kiwix-js-windows, and other UI improvements we started to discuss. Even if we are no UI/UX specialists, I believe that our UI is simple enough to fit into already-existing best-practices that we might follow
- We really need to go forward with libzim/kiwix-lib + emscripten. @kelson42 : we need some help on that. In particular on #509 (I gave all the steps to reproduce : if something is missing, please tell me)
- Ideally, I would put on hold the performance optimizations (cache etc) until we see how it behaves with emscripten. It should hopefully be much faster, and the libzim already includes some memory cache

**Comment by Jaifroid** [comment]
> @Jaifroid , if you're still interested in doing it, it would be great to improve the UI. By backporting some of the work you did for kiwix-js-windows, and other UI improvements we started to discuss. Even if we are no UI/UX specialists, I believe that our UI is simple enough to fit into already-existing best-practices that we might follow

Yes, I'm doing this in stages in #523, starting with #526 / #527. I think #527 is ready for review (I've just rebased it). Once we have Bootstrap 4 in place on our existing design, I can implement a test version of elements of the Kiwix JS Windows interface.

**Comment by kelson42** [comment]
I went through the older tickets and a few ones are of interested IMO:
* Add an easy way to report bugs #59
* UI Translation (this is on me) #13

**Comment by Popolechien** [comment]
I think a simple UI first step would be to get rid of most of the text on the landing page (or move it to a help subpage), leaving only a single big "open file" like there is on macOS (+also "Access library" pointing to download.kiwix.org/zim would not hurt). 
I'll have a look into #523 if I can.

**Comment by kelson42** [comment]
Should we keep that ticket open?

**Comment by Popolechien** [comment]
Sure why not.

**Comment by kelson42** [comment]
Because this ticket seems useless to me. It should be decided what comes in the milestone and then closed.

**Comment by Jaifroid** [comment]
We did actually merge a performance optimization over the summer, which was to add native Service Worker caching, as that was sorely missing and holding up development of the more modern Service Worker code. That is done.

What is an immediate priority is for me to work on UI, as we've agreed I should port the toolbars used in Kiwix JS Windows (approximately, there will be differences due to the different feature set) to Kiwix JS. This is going to take a bit of time because we are both extremely busy at the moment with RL (Real Life)... But I think we clearly know what we need to do, and unless anyone else thinks other issues should be opened as a result of this Wishlist, it can be closed.
