### ISSUE TITLE
Add an easy way to report bugs

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#59]
When an error occurs, we currently simply use the alert() function, and ask the user to report it.
We should provide a more user-friendly feedback, and an easier way to report the issue.

For example by providing a mailto: link with all the relevant info prepared in the body.
See for example http://www.webmasterworld.com/javascript/3290040.htm

The error itself might be displayed with Bootstrap alerts : http://getbootstrap.com/javascript/#alerts

But we probably need #43 (better error handling) to be fixed before implementing that

**Comment by kelson42** [comment]
Wow, a ticket from 2013! Not sure about the current validity of the ticket, but I would not recommend to invite users to send emails because it is not as efficient as opening a ticket here. I think this dialog should offer a link to open a ticket here... and maybe you want to create/update the new ticket template? This ticket ahould be easy to dix and actually might help easily to get more and better user feedback.

**Comment by Jaifroid** [comment]
There are no alert-based errors that I'm aware of left in the code... Errors do occur but are mostly swallowed in promises and reported only in console log. We do offer email support and also a link back to the GitHub issues in About, and the traffic is extremely light (one or two messages a year!). So if @mossroy agrees, I think this issue can simply be closed as no longer relevant.

**Comment by mossroy** [comment]
I agree : closing
