### ISSUE TITLE
When searching titles, scroll the page in order to see only what is necessary : the search field and the results

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#60]
At this moment, seeing the menu bar at the top is useless, and takes some space.
This space would be more useful to display search results.

Something like http://stackoverflow.com/questions/6677035/jquery-scroll-to-element should do what we need

**Comment by Jaifroid** [comment]
If I've understood correctly, I think this issue has been redundant now for a while, since we now float the results over the article, and with touch or mouse the whole window scrolls as we scroll down a long list of search results (i.e. the menu bar and the space it takes scroll out of view). With #501, also, the menu scrolls down with the keyboard.

Can we close this issue, @mossroy , or close it automatically when a version of #501 is approved?

**Comment by mossroy** [comment]
I think it's not really related to #501.
The idea was to automatically scroll the page to the relevant part (search results after running a search, or article content after choosing an article), so that all the available screen space can be used for it.
It might improve the usability on small screens.

**Comment by Jaifroid** [comment]
I think this would be superseded by #523, which uses a more compact design, and we wouldn't need to implement special scrolling. I'm closing but feel free to re-open if this is still wanted.
