### ISSUE TITLE
Introduce KiwixJS in Microsoft Edge app store

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#624]
This is a follower of #486.

Cot an email earlier from Microsoft inviting us to to put an Entry for "KiwixJS" in Microsoft Edge app store:

```
Don’t wait to Submit your Chromium extension(s) to the new Microsoft Edge browser through the Microsoft Partner Center.

 

I recently reached out to you on behalf of Microsoft as we are excited to have your extension on our new Chromium-based Microsoft Edge browser.

 

The new version of Microsoft Edge is off to a strong start – check out our announcement to adopt the Chromium open source project here.

 

The next version of Microsoft Edge will have a new Add-on experience and a new place where users will download extensions. This is a great opportunity for developers like you to target new users on Microsoft Edge. As we work toward getting the next version of Microsoft Edge ready for public release, we need your help to validate the extension submission experience is ready to go.

 

Check out the ideas we shared for the future of Microsoft Edge at Microsoft Build 2019.

 

If you’re interested in taking part, you can now submit your Chromium extension(s) to the new Microsoft Edge browser through the Microsoft Partner Center.

 

If you experience any difficulties along the way or have additional questions with the submission process, please reach out to ext_dev_support@microsoft.com for assistance.

 

We look forward to collaborating with you on our new browser!
```

@mossroy @Jaifroid Is that a topic you have already discussed? Does that sound a good idea? Woudl that be possible?

**Comment by Jaifroid** [comment]
Yes, it should be very easy. It's exactly the same format as the Chrome extension, as I understand it, maybe just tweak some variables in the manifest, and indeed I've installed the Chrome extension in Edge Chromium from the Chrome store. I guess it should probably be Kiwix JS rather than Kiwix JS Windows because the new browser is not just Windows.

**Comment by mossroy** [comment]
I agree with publishing kiwix-js to the new Edge store. It's a good idea, and should be easy.

Based on https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension , it should work out-of-the-box, with the same package.

@Jaifroid : if you feel like doing it, please do.

I suppose we should follow the same process as for Firefox and Chrome stores : 

- I suppose it happens here : https://developer.microsoft.com/en-us/microsoft-edge/extensions/
- We should create (if possible) a generic "kiwix-offline" account with contact@kiwix.org as its email. It probably needs @kelson42 and/or @Popolechien to confirm the account creation. Send the password to @kelson42 and me (if possible with a PGP encrypted e-mail). The idea is that the extension should not be manageable by only a single person
- The description and other info can probably be copied/pasted from other stores
- We should publish the latest official version : 2.7.0. I kept the unsigned zip file that had been uploaded for the Chrome store, if needed

**Comment by Jaifroid** [comment]
@mossroy OK, I'll see what I can do / find out. I think we should issue a new release as soon as I've had time to do the changes to #617. It would be worth issuing that release as a priority because of the bug that prevents correct loading of large ZIM files produced since May (#630 ). And the new release should be the one to go into the Edge extension store.

**Comment by mossroy** [comment]
+1 for a release when #617 is fixed, especially to have #630.
To me, it's not necessary to wait for a 2.8 to publish a 2.7 on Edge store, but as you like

**Comment by Jaifroid** [comment]
It seems there's a bit of account setup needed because the kiwixoffline MS account I have for publishing Kiwix JS Windows apps is not currently valid for registering for the Edge extension part of the same Dev Centre. I've written to @Popolechien separately about that, as he has the admin dev account.

The main reason for holding off on publishing 2.7 to the Store (apart from needing to set up the account) is that it could be a poor user experience if a new user finds the app, tries it on a recent ZIM, and finds it doesn't load correctly due to #630. They are likely not to bother with the extension again after a buggy experience. So I would prefer to publish one with the latest bugfix. I hope to complete #617 in the next couple of days, then if that goes smoothly, maybe we can prepare new release at weekend or next week.

**Comment by Popolechien** [comment]
I've signed up for an account and sent you credentials.

**Comment by Jaifroid** [comment]
The Edge extension is now published:

https://microsoftedge.microsoft.com/addons/detail/kiwix-js/jlepddlenlljlnnhjinfaciabanbnjbp

So I'm closing this issue.

**Comment by kelson42** [comment]
Here the ticket to update our web site. https://github.com/kiwix/web/issues/122

**Comment by kelson42** [comment]
@Jaifroid Can we side load the extension for edge? if yes, where is the file/package to sideload?

**Comment by kelson42** [comment]
@Jaifroid As we have released 3.0.0, I have to reask this question as this is still not clear to me if this is possible and how?

**Comment by Jaifroid** [comment]
@kelson42 I'm very sorry, I didn't see this quesiton from July before now. The answer is that the package format is exactly the same as the unsigned Chrome extension. It's the same package. You sideload it by enabling developer mode on the `edge://extensions/` page, then dragging and dropping the .zip file onto the page.

**Comment by kelson42** [comment]
@Jaifroid So weculd create a "edge" directory beside "chrome" with the exact same crxfiles and we whld be good?

**Comment by Jaifroid** [comment]
@kelson42 I think it would be better to put the unsigned .zip in that "edge" directory, because it is much easier to sideload an unsigned extension package in both Chrome and Edge nowadays. The file you need is https://download.kiwix.org/nightly/2020-10-08/kiwix-chrome-unsigned-extension-3.0.0.zip .

The reason it's hard to install a .crx is given in this article: https://techjourney.net/chrome-edge-disables-crx-installed-extensions-workarounds-to-turn-on/ .
