### ISSUE TITLE
Firefox extension (and Chrome extension) doesn't show Latex based formulas in newer ZIM files any more

### ISSUE THREAD

**Issue by florian29** [kiwix/kiwix-js#629]
Kiwix Firefox extension 2.7.0

Open the ZIM file wikipedia_de_all_maxi_2020-06.zim and go to the article "Satz des Pythagoras". You will notice that the mathematical formulas aren't shown:
![de 2020-06](https://user-images.githubusercontent.com/43439672/85920277-b9ba5380-b872-11ea-9d19-620cad38ec57.png)

With the older ZIM file wikipedia_de_all_maxi_2020-05.zim it worked properly:
![de 2020-05](https://user-images.githubusercontent.com/43439672/85920304-ed957900-b872-11ea-8630-2423d84aba75.png)

The same problem with the newer spanish Wikipedia ZIM file wikipedia_es_all_maxi_2020-06.zim:
![es 2020-06](https://user-images.githubusercontent.com/43439672/85920334-13228280-b873-11ea-863b-0093e9480afe.png)

The older ZIM file of this version wikipedia_es_all_maxi_2020-03.zim worked properly too:
![es 2020-03](https://user-images.githubusercontent.com/43439672/85920355-4402b780-b873-11ea-9abc-383bf5b1805c.png)

**Comment by Jaifroid** [comment]
Hello @florian29, I am just downloading this ZIM to take a look.

**Comment by Jaifroid** [comment]
@florian29 I confirm that this ZIM (or at least the article you've pointed us to) does not contain the SVG fallback images, but it does contain the MathML as you surmised. Kiwix JS cannot read MathML in a ZIM. However, the sister version Kiwix JS Windows can. You can test that for yourself here in Chromium or Firefox:

https://kiwix.github.io/kiwix-js-windows/ 

Make sure the setting to use MathML is set in Config (it should be as it's default).
![image](https://user-images.githubusercontent.com/4304337/85923008-6f8b9f00-b87f-11ea-9c36-acbfaac63c0b.png)


![image](https://user-images.githubusercontent.com/4304337/85922987-318e7b00-b87f-11ea-9b2c-92f2d06c9fb3.png)

**Comment by Jaifroid** [comment]
If you are interested in that and are using a PC, you can get a portable version of the app here:

https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.97N

Or if you are using Windows 10, then it's also optionally available in the Store:

https://www.microsoft.com/store/apps/9P8SLZ4J979J 

or from GitHub if you're prepared to sideload:

https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.99-beta

For any of these, you just need to pick your ZIM file once from Config, and it will remember your choice in subsequent sessions.

**Comment by florian29** [comment]
> Hello @florian29, I am just downloading this ZIM to take a look.

@Jaifroid Thank you for caring about this issue. Are you sure you've loaded the newest ZIM file "wikipedia_de_all_maxi_2020-06.zim"? Or maybe you've loaded the older one "wikipedia_de_all_maxi_2020-05.zim"? Because I've tried what you've suggested, to open it with
https://kiwix.github.io/kiwix-js-windows/
and it was not possible to open the new ZIM file from 2020-06. Nothing happened when trying to open it. The same issue happens with these newer ZIM files with Kiwix Desktop for Win64. I reported this issue there:
https://github.com/kiwix/kiwix-desktop/issues/458

The older ZIM file from 2020-05 opens without problems. And also the formulas where shown. But this was never a problem with the older ZIM files, as the Kiwix Desktop Win64 opens them and shows the formulas too (and the Firefox Kiwix extension too).
The only way I found to open at least the newer ZIM files (from 2020-06) was with the Firefox Kiwix extension, but with the restriction that the formulas weren't shown.

I've tried it also with the portable version from
https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.97N
and I experienced the same results (2020-06 doesn't open; 2020-05 opens without problems).

The same problem occurs with the new spanish ZIM file wikipedia_es_all_maxi_2020-06.zim, and also the older version of this ZIM file wikipedia_es_all_maxi_2020-03.zim opens without any problems (with Kiwix Desktop for Win64, with Kiwix JS and also with Android).

**Comment by Jaifroid** [comment]
@florian29 I was using the correct ZIM file which I had just downloaded. But you are reporting an issue which I believe is to do with a bad encoding of these files. I am currently investigating, but my preliminary investigation is that there is something wrong with the [URL Pointer Position bytes](https://wiki.openzim.org/wiki/ZIM_file_format#URL_Pointer_List_.28urlPtrPos.29) in the ZIM file header of these new files. I wonder if @kelson42 knows something about that. I'm getting a crazy value for `urlPtrPos` on ZIMs encoded in June. I think this issue explains also #621 and #628 .

The thing that explains why I can open the same ZIM and you can't may just be memory allocation. Basically, the reader is trying to seek through the entire file to get the URL Pointer List.

This may be an incorrect assumption in Kiwix JS (and the Windows version), or it may be that these ZIMs have a badly encoded header. I am investigating!

**Comment by Jaifroid** [comment]
@florian29 If you're interested in a technical explanation of why that ZIM is failing both on Kiwix JS / Windows and on the desktop app, see my latest comment in #628.

**Comment by Jaifroid** [comment]
@florian29 I think I have a fix for you (based on comment in #628). Please follow this procedure to test:

Visit https://kiwix.github.io/kiwix-js-windows/ , and open Dev Tools (press F12 or Ctrl-Shift-I in Chrome). Force reload by pressing Ctrl-Shift-R. You can now close Dev Tools.

Now pick your file `wikipedia_de_all_maxi_2020-06.zim` and load the Pythagoras page. It should now work. If not, please exit your browser completely and repeat these instructions (the point is we have to clear the Service Worker cache for you to see the changes straight away to be able to test properly).

If you can load the page, please do one more test: go to Config and under Expert Settings, instruct the app to use the SVG fallback images (see screenshot). Return to the page using the provided link `<< Return to Satz des Pythagoras`, and you should now see the fallback SVGs being (slowly) loaded from the top of the page. **NB if using Chrome / Chromium / Edgium, then these images should show pretty rapidly. However if using Firefox, you might have to wait quite a while for the images to start loading.** If that test works, let me know: it means what I wrote in #628 is correct.

I have tested these instructions in Edge Chromium (new Edge) and in Firefox.

NB after testing the SVG fallbacks, you might want to turn TeX / MathML rendering back on, because it's a lot faster.

![image](https://user-images.githubusercontent.com/4304337/85939894-f63c8c80-b910-11ea-81f1-9f142922bd7e.png)

**Comment by florian29** [comment]
> @florian29 I think I have a fix for you (based on comment in #628). Please follow this procedure to test:

@Jaifroid I reproduced all the steps exactly the way you described and it works (with some restrictions I will explain further). I can open the ZIM file and the formulas are shown for KaTeX as well as for SVG settings. I tested it also for the spanish ZIM file (wikipedia_es_all_maxi_2020-06.zim) and it works too.

Now the problem: When you open articles with bigger formulas (or formulas which need more space), such as "Maxwell-Gleichungen" or "ecuaciones de Maxwell" for the spanish ZIM, you will notice problems in the visualization of the formulas when using the KaTeX setting. I will paste you a screenshot:

![Sin título](https://user-images.githubusercontent.com/43439672/85943272-56422b80-b92f-11ea-815e-5c2d5ef4a264.png)


But when you use the SVG setting everything is shown correctly:

![Sin título1](https://user-images.githubusercontent.com/43439672/85943293-707c0980-b92f-11ea-8b1c-d4c45f737c69.png)

Maybe you could take a look if this can be solved too. But at least the SVG setting works and it doesn't take a lot of time with Firefox, the formulas appear very quickly.

Do you think that this can be fixed also for the Kiwix Desktop for Win64 program? Thank you in advance.

**Comment by Jaifroid** [comment]
Thank you for the full and helpful report @florian29 . I'm very pleased to hear the patch works for you and allows you to view the Spanish Maxi file too (I was actually in the process of downloading that one to test it for a different reason). I'm particularly pleased to hear the SVGs are showing quickly in Firefox: I don't know why I saw serious slowdown in my copy, but could have been a glitch.

Regarding the inaccurate visualization of TeX / MathML, I think this is down to KaTeX. I switched from MathJAX to KaTeX due to some major issues I was having with fonts in MathJAX wanting to download from a third-party site and causing CORS errors in Firefox in a number of circumstances. This despite the MathJAX installation being fully local inside the app. However, TeX / MathML was originally provided because on mobile decompressing SVGs used to be excruciatingly slow. They even used to crash the app. Optimization over the past couple of years has improved this radically even on mobile, though the PWA version of Kiwix JS Windows on Android can still be slow.

Please note that Kiwix Desktop and Kiwix JS (as opposed to Kiwix JS Windows) have **never** supported TeX/MathML rendering. They simply use the SVGs. It will take a while for the fix mentioned here to work its way through to release on those apps, or else it may be that the ZIM format issue I've identified will be fixed at ZIM level instead. I'll release an update of Kiwix JS Windows portable app and store app as soon as I can, as it can be used until the other apps or ZIMs are fixed, or the PWA version can be used right now.

Regarding TeX rendering, maybe I should change "recommended" to "experimental" for the TeX setting, or provide clearer warning about potential inaccuracy. I'll take a look at whether those issues have been solved in more recent releases of MathJAX, but this will take time. In the meantime, clearly I'd recommend using the SVG setting for your use case.

Will let you know of any update/progress here.

**Comment by Jaifroid** [comment]
@florian29 Just to keep you informed there is now a PR to fix the issue with reading new ZIM files in Kiwix JS (the fix is already in Kiwix JS Windows master branch). It is #630. It doesn't make it possible to read TeX strings in Kiwix JS, but that's not really needed if the SVGs can be shown again. When that PR is merged this issue will close, but it will take a little while for the fix to work its way through to a new extension release. Till then, you could use the PWA version of Kiwix JS Windows if you want (this has the fix).

**Comment by florian29** [comment]
@Jaifroid Thank you! I've downloaded it yet and it works! Would be nice if someone could fix the Kiwix Desktop program for Win64 too, so we can perform a fulltext search. Maybe this is not your business but perhaps you can instruct the guys how to fix it. Thank you in advance!

**Comment by Jaifroid** [comment]
@florian29 The desktop version should be fixed as soon as the patch already made to libZim makes its way through to a release. There is always some latency there, I'm afraid because it involves re-building the app. It's not my area, but the patch has been merged in the underlying library, so it will make its way through eventually.
