### ISSUE TITLE
Interface translation

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-js#645]
I would like to translate the **Kiwix extension** for web browser into Russian. In particular I want to translate the **four** lowest icons into Russian:
![Kiwix-extension-for-web-browser](https://user-images.githubusercontent.com/65112331/88451893-08074600-ce63-11ea-9108-9220bbc53059.png)

**Home** — **Домашняя страница**
**Back** — **Назад**
**Forward** — **Вперёд**
**Top** — **Наверх**

**Comment by Jaifroid** [comment]
Thank you, @Ubuntu-2020 . We have #13 for interface translation. It wouldn't be enough just to translate the icons, we would need it to be part of a full UI translation solution. If you are prepared to tackle #13 for Russian, that would be great. Please note we have not fully decided on a translation library, but research a couple of years ago indicated that `jQuery.l18n` might be a good library because it is (was?) maintained by WikiMedia. However, things change fast, so it might be good to do the research again. Please see that thread, and add any comments there.
