### ISSUE TITLE
Can't save an image in the Kiwix extension

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-js#694]
You can't save an image from a Wikipedia article in the Kiwix web browser **extension**.
After clicking on the **Save Image line**, absolutely nothing happens:
![Kiwix Save Image](https://user-images.githubusercontent.com/65112331/103541460-20fd3400-4ea4-11eb-8d5c-6225e015c855.gif)

**Comment by Jaifroid** [comment]
@Ubuntu-2020 I can't reproduce this behaviour for the Chromium extension in Windows 10. Could you confirm which browser extension you are using and which version of the browser? Also, have you tried switching to Service Worker mode in Configuration (if available for your browser)? (Having said that, it works in both jQuery and SW mode in Edge Chromium on Windows 10.)

**Comment by mossroy** [comment]
I reproduce this issue on both Firefox and Chromium (on Ubuntu 20.04)
On Firefox, it indeed does nothing (and there is no error message)
On Chromium, it asks for a file location, but does not create the file and displays a "network error"
Same behavior in jQuery or ServiceWorker mode

**Comment by mossroy** [comment]
I also reproduce the issue on latest Firefox and Chrome inside a Windows 10 VM.
@Jaifroid : it's surprising that you don't have the same behavior?

**Comment by Jaifroid** [comment]
Apologies, I have to confess I didn't get as far as actually making the save, I simply verified that the Save As... dialogue does indeed show and asks me to pick a location. However, it cannot then save after it attempts to download the Blob. I have the same behaviour as you describe above, @mossroy . In jQuery mode, I guess this is because we delete the BLOB URLs as soon as they are loaded in uiUtil.js. A simple experiment would be to comment out these lines:
```
            node.addEventListener('load', function () {
                URL.revokeObjectURL(url);
            });
```
Alternatively, we can make Data URIs, which should work universally (in jQuery mode). Note that for browsers that do not support WebP, we make Data URIs in any case.
Of course this would not solve the issue for SW mode.

**Comment by Jaifroid** [comment]
PS Remember we have code that allows a user to download a PDF (in JQuery mode) from the ZIM -- could be leveraged, though I think dataURIs for images would be the best solution. I'm surprised it doesn't work natively in SW mode, though, and that means there might be somthing else blocking download. Code isolation of extensions?

**Comment by mossroy** [comment]
It's not related to browser extensions : there is the same issue when running kiwix-js through a local webserver or through https://kiwix.github.io/kiwix-js/

When using Firefox in SW mode from https://kiwix.github.io/kiwix-js/, it manages to download the images, but the result is corrupt : the downloaded file contains a 404 error page from github.
So I suspect the browser tries to download the image without getting through the SW

**Comment by kelson42** [comment]
From a user perspective, this is a serious bug IMO.

**Comment by Jaifroid** [comment]
I can now confirm that the reason it doesn't work in both jQuery and SW mode is simply because we revoke the BLOB as soon as it is displayed. I have an option in Kiwix JS Windows that allows the user to export the entire page, including images, to a self-contained html file. This option inserts all images as dataURIs. When this option is enabled, images can be downloaded even in jQuery mode. We can easily implement dataURI image insertion instead if all platforms support it. It would only be a few lines to adjust in the code. I have some vague memory of dataURIs being banned in some contexts possibly in Firefox OS apps? But that probably wasn't for images: it was for CSS I think. I **believe** images should be fine, but only real way to know is testing it.

**Comment by mossroy** [comment]
It might be possible to workaround that in jQuery mode with dataURIs, but probably at the cost of a much higher memory (and CPU?) consumption : the images (and videos?) content would be serialized in the HTML!

In ServiceWorker mode, I don't see how to handle this for now. Browsers seem to not go through the ServiceWorker when downloading images or videos.

**Comment by Jaifroid** [comment]
I used to think dataURIs would consume lots of memory, but my experience in both mobile context and browser context is that it's not an issue in practice. This can be tested by visiting pwa.kiwix.org, and turning on the Configruation option **Add breakout link to open _current_ article in new (non-browsable) window**. This inserts all images as dataURIs (in jQuery mode, not working in SW mode). In mobile context this is just as fast as using BLOBs. With the inserted breakoutlink, the html can be exported to a self-contained browser page. Images can be downloaded by right-clicking (again, this is in jQuery mode).

**Comment by mossroy** [comment]
I might be wrong about memory consumption, I did not check.

A workaround for this issue could be to use "Copy image" after a right-click on the image you want to download, then paste it in another software (image editor, word processor, or whatever you like). It seems to work well, at least on my computer, on latest Firefox and Chromium.
Could you test on your sides?
It's clearly not ideal, but works for me. We could at least document that.

Implementing a jQuery-specific solution would not be a good move, as we discussed earlier, and would not ease the transition to SW mode by default.

If we believe it's not the right behavior of browsers (in SW mode), we could submit bugs on them. But the fact that it behaves the same on Firefox and Chrome will not help

**Comment by Jaifroid** [comment]
Yes, that workaround works in Edge. I agree it would be good to document.
As I mention in the linked issue on Kiwix JS Windows, I already have a system for inserting all images as dataURIs downstream, so I'd like to expose that as an option there. I agree here that we can document the workaround, perhaps via a tooltip.
