### ISSUE TITLE
Mobile view of a zim file isn't supported

### ISSUE THREAD

**Issue by sujit-jaunjal** [kiwix/kiwix-js#706]
The information on the right hand side of the image isn't displayed when switched to the mobile view. Just the image is shown and there's just blank spaces below.

![Screenshot (2)](https://user-images.githubusercontent.com/78826399/108631812-c3dc3280-7491-11eb-852b-10bc984590b8.png)
![Screenshot (1)](https://user-images.githubusercontent.com/78826399/108631816-cc346d80-7491-11eb-8377-1dbc879f165c.png)

**Comment by Jaifroid** [comment]
Thanks for the report. I think this may be "by design", i.e. a stylesheet rule prunes certain optional information if the sxcreen size is smaller than a certain size. There is a actually a lot of information suppressed in the mobile stylesheet which can't even be seen full-screen, like navboxes and topic overviews and topic Portals. They are in the code, but are suppressed by the mobile stylesheets that MWOffliner chooses to use to compile Kiwix ZIMs from Wikipedia. You can reveal this extra information by switching to a Desktop stylesheet, but that can only be done in readers that have a desktop view. One example is https://pwa.kiwix.org  - you'lll find a Desktop style view in Configuration, but this has not been tested with Russian-language ZIMs, so not guaranteed to be exactly the same as Wikipedia's desktop view.

**Comment by sujit-jaunjal** [comment]
So should anyone wok on it or not ?

**Comment by Jaifroid** [comment]
I don't think this is the place to work on it. It is undoubtedly not an issue with our reader, but (if it is a bug at all) it should be reported to mwoffliner here:

https://github.com/openzim/mwoffliner/issues 

Have you tested it on other Kiwix clients, to see if the issue is a general one with the ZIM format? I'll close for now, as we can't fix this here, but feel free to re-open if you think it's a problem with the client (Kiwix JS) rather than the ZIM.
