### ISSUE TITLE
File selection dialog appears twice

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-js#707]
Sometimes my browser's file selection dialog appears twice before moving to the home tab.

# Procedure

1. Click to open the Kiwix extension (it will open to the configure tab)
2. Click on the "Choose File" button (I am using a touchpad so I might be clicking more than once)
3. Use the dialog to choose a valid file

# Actual behaviour

The dialog appears again.

After choosing the same file in the second dialog, I finally get to the home screen.

# Expected behaviour

I should see the dialog only once if the file is valid, and go directly to the home screen.

I'm guessing the button is async or something, so a solution would be to make the button only accept one click every second.

# Environment

Kiwix-js: `3.1.0` from Chrome Web Store
Browser: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36`

**Comment by Jaifroid** [comment]
@danielzgtg Thanks for the report. I have to say that I've never seen this behaviour on the OS's I test on. This is probably a system or a browser issue, because the dialogue box is not one we have programmed in any way. It is the standard file selection dialogue box for all browsers, and it cannot even be invoked programmatically, only via a user action. The one thing we could do is to disable the file-select button for, say, 500ms after it has been pressed. Could you please confirm whether this is a Linux OS as might be inferred from the browser string? If so, maybe @mossroy can try to reproduce, as I personally don't have a running GUI Linux system to test on.

**Comment by danielzgtg** [comment]
> Linux OS

Yes

> browser issue, because the dialogue box is not one we have programmed in any way

Never mind. It seems like it's indeed a Chrome issue. Since the problem also occurs on https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file , this isn't Kiwix's fault

**Comment by Jaifroid** [comment]
OK, thanks @danielzgtg , it would indeed be better to get it fixed globally by reporting the bug to the Chrome devs for Linux.
