### ISSUE TITLE
Kiwix-js detects "active content" on some new ZIM files, in jQuery mode

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#746]
If you open http://tmp.kiwix.org/alcohol_meta_stackexchange_com_2021-08.zim in jQuery mode, it displays the "active content" warning popup.
Maybe we should consider white-listing this kind of ZIM files, as they mostly work properly, even in jQuery mode?

It should be decided when they're finalized (it seems they're not yet)

**Comment by Jaifroid** [comment]
Yes, I noticed that. If that's a common js file being detected that is of no consequence, we can add it to the exclusion regex.

**Comment by Jaifroid** [comment]
I-ve changed the title of this issue, because I see that the new mdwiki ZIMs also display the "active content" warning in jQuery mode. They don't show this warning on Kiwix JS Windows, so I must have massaged the regex that detects this content (though I only have a vague recollection of doing it...). I'll backport.

<img alt="image" src="https://user-images.githubusercontent.com/4304337/183407500-adb48c41-1105-4895-abc5-2a5ac5adc398.png">
