### ISSUE TITLE
Add a step in our CI to check the list of pre-cached files for the PWA-ServiceWorker

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#772]
It should be possible to compare the list of files that exist in www directory, and the list of pre-cached files in service-worker.js file.

If one file is missing, it should break the CI

**Comment by Jaifroid** [comment]
I'm wondering how this would work. Wouldn't we need to provide a list of files needed by the app for the testing engine. In which case, how is that different from providing the list of files in `service-worker.js`? We would then have to maintain two lists of files instead of one?

I did think maybe we could use Node APIs to read the contents of the `www` directory, because we probably (though not necessarily) need all the files that are in that directory and subdirectories. However, we also need some files that are not in that directory, but not all of the files. The needed files are listed in our dockerfile, but I'm not sure how easily it translates into a format Node APIs can use.

**Comment by mossroy** [comment]
My idea was to read the list of files in the www directory, apply some additions/exclusions if necessary, then compare this list with the hard-coded list of cached files.
In the CI, we are free to use the technology we want to do that (not necessarily javascript). It might be a bash script for example

**Comment by Jaifroid** [comment]
#774 is implemented and working. However, it can't be merged until #771 is merged (and then it may need to be rebased on master).
