### ISSUE TITLE
Kiwix-JS not reading Nautilus-based zim files

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js#785]
[Nautilus](https://github.com/openzim/nautilus) is a scraper that allows us to package a bunch of documents (PDF, Word, videos) together in a zim file. 
I recently tried to open https://mirror.download.kiwix.org/zim/other/zimgit-post-disaster_en_2021-12.zim in my chrome browser (Kiwix-JS 3.2.0) and to my surprise (and dismay) the file could not be read.

This is a small but growing segment of content we have to offer, so I wanted to enquire if there was any chance that nautilus files could ever be read or if there is some major JS-related blocker that will always prevent it from happening.

**Comment by mossroy** [comment]
Did you try with ServiceWorker mode instead of the jQuery mode?
You can switch to it in "Configuration" section, "Expert settings".

**Comment by mossroy** [comment]
I could test your ZIM file, inside a Chromium extension.
The ZIM file uses javascript, so it can't work in jQuery mode.
But it also doesn't work in ServiceWorker mode because there is some inline javascript in home.html (line 82), which is rejected by the CSP of browser extensions : 

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-PtO5L7mz44xgm8o7YDaYSxpBLHPVArwXn4bgl0rjzNw='), or a nonce ('nonce-...') is required to enable inline execution.

The solution is to update Nautilus to remove inline javascript, and move it in separate javascript files.
For this line 82, I suppose it should be easy to do, but It don't know if there are other inline javascripts generated by Nautilus.

I'll create a ticket on Nautilus

**Comment by Popolechien** [comment]
@mossroy yes, to no avail

**Comment by mossroy** [comment]
I just created https://github.com/openzim/nautilus/issues/34 to consider fixing that in Nautilus

**Comment by Popolechien** [comment]
Thanks a lot.
