### ISSUE TITLE
On some devices that do not support ServiceWorkers, a warning is displayed on every run

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#814]
At least it's the case on my Firefox OS device.
Each time I start it, it says "The ServiceWorker API is not available on your device. Falling back to jQuery mode". It's true, but I don't see why it's trying to switch to SW mode.

window.location is "app://kiwix.org/www/index.html" on this device, and it's using Local Storage.

**Comment by Jaifroid** [comment]
Oh, how strange. It must be that `isServiceWorkerAvailable()` is returning true, as it's not supposed to attempt SW mode without that returning true...

I long since lost the portable Firefox that could run the simulator. Can you remind me which one still works, and I'll try to debug before 3.3. Or we can revert that PR for now if I can't find the cause (but seems unlikely it's anything complicated!).

**Comment by Jaifroid** [comment]
(It's also strange that it would run with a protocol of `app`, as I explicitly selected only `^https?`....).

**Comment by mossroy** [comment]
I'll try to investigate today

**Comment by Jaifroid** [comment]
OK, I was wondering if this is happening on the branch with the asynchronous systemAlert, or on master as well. If on the latter branch, it could be because of the alert system not being fully nailed down yet...

**Comment by mossroy** [comment]
I was on the branch. I'll test again on master

**Comment by mossroy** [comment]
Same issue on master.
After some debugging, I found the problem.
It's line 98 of app.js, where you set the injectionMode, and handle a default value if not already in settingsStore.
There are missing parenthesis that change the behavior.
I create a PR

**Comment by mossroy** [comment]
It reminds me that it's still valuable that I test on this very old device.
Not because it's crucial to support it, but because it helps discover some bugs or issues (like performance ones)
