### ISSUE TITLE
Images are not displayed loading ZIMs with WebP format images in icecat 60.7

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#835]
Issue reported by a user via email. I have been able to reproduce it in icecat running in WSL-Ubuntu (Windows 11). The images are being inserted as data URIs rather than as BLOBs, which indicates that this version is using the polyfill to read WebP.

![image](https://user-images.githubusercontent.com/4304337/153369236-312451b0-1ba4-48a7-bbf3-abf41d0a1e30.png)

**Comment by mossroy** [comment]
I tested with IceCat 91.5.0esr (on windows 10, using an unofficial build from https://github.com/muslayev/icecat-win64) and I don't reproduce the problem (using https://download.kiwix.org/zim/wikipedia/wikipedia_en_ray_charles_maxi_2022-01.zim), using kiwix-js extension 3.3.0.
Of course, this version of IceCat supports webp. But I also tested with webp disabled (it's possible to do that: in `about:config`, you can set `image.webp.enabled` to false): I see that the polyfill converts the webp image to png, and displays it fine.
It does not seem to come from built-in LibreJS extension (which does not says it blocks anything)

I also tested with IceCat 60.7 and 60.8 (on Windows 10), and reproduced the original issue.

**Comment by mossroy** [comment]
IceCat 60.7 does not seem to block all dataURIs: the image is properly displayed on https://dopiaza.org/tools/datauri/examples/index.php

**Comment by Jaifroid** [comment]
Hmm. So maybe it just can't cope with data URIs inserted after first paint? Yet we do know it can cope with BLOBs inserted at the same point, because that is how it works with ZIMs prior to WebP. This is where we insert the data URI:

https://github.com/kiwix/kiwix-js/blob/master/www/js/lib/uiUtil.js#L55

It would be a case of adding a step to convert the data URI to a Uint8Array, and then continuing with the insert BLOB part of the same function. It might even be cleaner, because we would know this uiUtil funciton will always produce a blob, rather than sometimes producing a dataURI. The name of the function is `feedNodeWithBlob` (currently inaccurate!).

Of course it still might not work, but theoretically it should.

**Comment by mossroy** [comment]
It does not come from when the image is painted: I could reproduce with a local copy of one of our dataURI image, copied from devtools of IceCat 60.7 into a single HTML file.
What is more surprising is that opening the same HTML file on Firefox 97 fails too.
So there might be something wrong in the base64 encoded png?

If I disable webp on Firefox 97, and copies the same HTML tag, the content looks different (but I did have the time to check in detail), and it displays correctly (even on IceCat)

Could it be a bug in webpHero, that only happens on IceCat?

**Comment by Jaifroid** [comment]
Interesting. The only other browsers I have to test the WebP conversion on are IE11 and Edge Legacy (testing on Windows Mobile, as it can no longer be installed on any Windows desktop). Also IE mode in Edge Chromium. In IE11 the dataURIs (which are very very long) are inserted and the images show fine. But there is an error logged in the WebP machine. I didn't see the error (or maybe I wasn't looking hard enough) in IceCat. One of those errors just seems to be about a missing image. But the other (the first one) is a bit more suspicious (just `undefined`). It's probably nothing.

![image](https://user-images.githubusercontent.com/4304337/153599068-20de118d-a830-46c9-82b8-e18209fc8772.png)

**Comment by mossroy** [comment]
I do not see any error message on IceCat 60.7 (with latest Ray Charles archive)
I tested on Firefox 60.7 ESR (which should have the same gecko version as IceCat 60.7): I don't have the issue on images. And it's much faster (maybe because of the many extensions bundled in IceCat?)

On IceCat 60.7, if I put a breakpoint in uiUtil where it decodes webp images, the uri is:
`uri: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANwAAADcCAYAAAAbWs+BAAACeElEQVR4nO3TMQEAMAyAsPo3vbpgRxMFPMwDMvM7AC4xHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMByHDQchwEDIchAwHIcNByHAQMhyEDAchw0HIcBAyHIQMB6EFHG934J1clgwAAAAASUVORK5CYII="`

On Firefox 60.7, same image, same breakpoint:`
`uri: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANwAAADcCAYAAAAbWs+BAAAgAElEQVR4nIzbdXAcaYL3+Y64uPcuNi7ubndmZ7tnunu6zRZDMVeJuVQqVYklW7ZlEDMzc4llyTIzMzPIJMuyLUYztHtgZ2eH3+/9IY9m+n037p0/PpGVlZmVkVn1eyCfpz4bvzHI1N0hZoeeMjb4kIcPr/Bk7BZD4ze4dvck126f5NHjWwwM3OLWzUvcvXONgYd3GBzoZ3Cgn8eP7vL40V2GHt9bWJ8Yf8rE+FOGHt/j8aO7PH3ykKdPHvJk6P7Ce399f3R4kJFnjxgc6Ode/3Vu3rjI9avnuXzlLJeunePKrYtcuXWRc9fOc/bqWc5dvciFG5e5cP0ql29d5+qdW1y+dZ0zly5x5tIlLl+/xY0797h55yG37g7Qf/cRd+8Ncu/BIHfvDXC3/yEP7g8yMPiYR4+HePBogPsDD3k4NMCjZ48ZHn3G2OQYUy+mmHk5zczzKabnJpiZnTc38zfP56aYmhxlcOAeQ4MPmJkaY2pylLGRJ4yNPGF0eIjR4SFGnj3m2fDfjIw+YWT8KWOTI0zMjDE9N8HUi6l5s+OMT40yNj1vfGre1PQYU9NjC+eYmhxlcmKE8dGnC+eaGB/mxcwEc1PjTI4+ZeTJIMODDxl5/IjxJ4+ZeDrE1MhTpkeHeT4xxvOJMWYn/2ZmYpTZsRGmR4eZGX7K9LMnvBof4zfv3vLrN6958WyYucdDvB0d493EBG/Hx3k3McH7ySneTc17Mz3Fq5kpXs5O8Xxuirm5KWaeT/3t+j6ZeT7v+fNpnj+f5uWLGV6/nOXNqznevn7O27cvefV6jtkX08y+mOb52zlevn/J7Ns5pl/PMPtqhpmX00y9mGLy+QTTcxPz93JmnJevZvn44Q2/+PiOX3x4y8d3r/nu7Ss+vHnJh1fPef9yjnfPZ/8h/OkPfHj1nFcTk/zi9Rt+8e…"`
(the string is truncated)

With IceCat, I see that the base64 String has a repeated pattern, which looks suspect to me (and does not render)

**Comment by Jaifroid** [comment]
Excellent sleuthing! So, converting to a BLOB would not work, clearly. Very curious. I guess the repeated pattern is `EDIchAwHIc`.

**Comment by mossroy** [comment]
It would be good to test the webp-hero demo with IceCat 60.7, but it's no longer on https://chasemoskal.com/webp-hero/
It should be possible to reproduce it locally with a checkout of the source code https://github.com/chase-moskal/webp-hero and a `npm start`, then browse http://localhost:5000/ with IceCat.
It would be a way to prove (or not) that it's an issue between IceCat and webpHero

**Comment by mossroy** [comment]
I can confirm that the demo of webp-hero does not work on IceCat 60.7 (with no error in console log)
![image](https://user-images.githubusercontent.com/890923/153713811-04ff1875-2564-4aef-ba3a-b213031de4de.png)
even after disabling all addons:
![image](https://user-images.githubusercontent.com/890923/153714112-26b64553-e005-4555-845e-012592c56aed.png)

where it properly works on Firefox 60.7 (that does not natively supports webp either. I could check with devtools that the webp image is replaced by the png dataURI)
![image](https://user-images.githubusercontent.com/890923/153714220-77268dff-4d27-4f3e-a916-6436c53c3eca.png)

**Comment by mossroy** [comment]
I've opened https://github.com/chase-moskal/webp-hero/issues/43 for that

**Comment by chase-moskal** [comment]
if you need to decode directly, i've exposed the function `webpMachine.decodeToCanvas(canvas, webpData)`

https://github.com/chase-moskal/webp-hero/blob/master/source/webp-machine.ts#L43

**Comment by mossroy** [comment]
Many thanks @chase-moskal for investigating and releasing a new version so quickly!
An anti-fingerprinting feature of IceCat could likely be the root cause. I suppose they have improved this feature in more recent versions of IceCat.

I've upraded to dev.28, but it was not enough.

The reason is that we don't run `.polyfillDocument()`, but instead convert the images ourself.
If I remember well, it's because we inject the webp binary as a blob (because we read in the ZIM file), so our images look like:

```
<img data-kiwixurl="I/Lovemetonight.jpg.webp" decoding="async" data-file-width="300" data-file-height="300" data-file-type="bitmap" loading="lazy" src="blob:moz-extension://c33b55f3-9e5c-4ecb-8204-052a23c7e4d3/ef2d063d-c3ae-45b5-8b09-b170f37d1b95" width="220" height="220">
```
which is probably not handled by `.polyfillDocument()`.

I managed to make it display an image on PR https://github.com/kiwix/kiwix-js/pull/838, by using the `.decodeToCanvas` you mentioned, so it's promising.

But it raises `Error: cannot decode when already busy` when there are many images.
It's logical: `.decodeToCanvas` runs asynchronously, and does not allow several image conversions in parallel.

We would probably need a function similar to `.decode`, that would return a Promise, so that we can make sure to handle images sequentially.

**Comment by Jaifroid** [comment]
Just to clarify, we can't use `polyfillDocument` becasue we have to extract each image from a compressed archive. The URLs have to be processed by us first. Once we have each image's content as a `Uint8Array`, we use `webpMachine.decode()`. We then insert the resulting dataURI into the node ourselves:

```
            webpMachine.decode(content).then(function (uri) {
                // DEV: WebpMachine.decode() returns a data: URI
                // We callback before the node is set so that we don't incur slow DOM rewrites before processing more images
                if (callback) callback(uri);
                node.setAttribute(nodeAttribute, uri);
            })
```

**Comment by chase-moskal** [comment]
@Jaifroid @mossroy 

in the fresh release `webp-hero@0.0.1`:
- static functions for are now available
  - `WebpMachine.replaceImageWithCanvas`
  - `WebpMachine.cloneCanvas`
- after some fidgeting, i think i've managed a solution that seems to work well:
  - [replaceImageWithCanvas](https://github.com/chase-moskal/webp-hero/blob/e4bd83c5f1c35490b1d9575b59200d89227d95b0/source/webp-machine.ts#L43)
      ```ts
      /**
       * Replace an <img> element with a <canvas> element
       */
      static replaceImageWithCanvas(image: HTMLImageElement, canvas: HTMLCanvasElement) {
        canvas.className = image.className
        canvas.style.cssText = window.getComputedStyle(image).cssText
        canvas.style.pointerEvents = canvas.style.pointerEvents || "none"

        const imageWidth = image.getAttribute("width")
        const imageHeight = image.getAttribute("height")

        canvas.style.width = image.style.width
          || (imageWidth
            ? `${imageWidth}px`
            : "auto")

        canvas.style.height = image.style.height
          || (imageHeight
            ? `${imageHeight}px`
            : "auto")

        const parent = image.parentElement
        parent.replaceChild(canvas, image)
      }
      ```
- as seen on the new [webp-hero live demo](https://webp-hero.chasemoskal.com/?force?useCanvasElements), this seems to be somewhat robust against images with different sizes applied in different ways:
  - `<img alt="" src="images/landscape.webp"/>`
  - `<img alt="" width="300" src="images/dice.webp"/>`
  - `<img alt="" style="width: 800px" src="images/firebreather.webp"/>`
- [`cloneCanvas`](https://github.com/chase-moskal/webp-hero/blob/e4bd83c5f1c35490b1d9575b59200d89227d95b0/source/webp-machine.ts#L68) can be used to copy a cached canvas, to avoid decoding the same data multiple times
- tested in icecat and chrome

**Comment by Jaifroid** [comment]
@chase-moskal Excellent, thank you! We'll try out new release!

**Comment by chase-moskal** [comment]
@mossroy the static functions will be available on the constructor.

```js
// access the function directly on the constructor function
WebpMachine.replaceImageWithCanvas(image, canvas)

// you may find the constructor on the webpHero object,
// depending on how you loaded webp-hero
webpHero.WebpMachine.replaceImageWithCanvas(image, canvas)

// access the function from an instance
webpMachine.constructor.replaceImageWithCanvas(image, canvas)
```

**Comment by mossroy** [comment]
Thanks @chase-moskal , it's working fine through the constructor.

Our main concern now is to know when we should use `decodeToCanvas` instead of `decode`.
If we don't find a reliable way to detect that, we'll add a setting in the app. By default, it would use `decode`.

**Comment by Jaifroid** [comment]
@mossroy Looking at the source code for WebpMachine, I think we should always use `decodeToCanvas()` because we can then extract a BLOB from the canvas in non-anti-fingerprinting browsers, instead of a dataURI. The reason this isn't any kind of degradation is that `decode()` actually calls `dcodeToCanvas()`, waits for its result and then does `canvas.toDataUri()`. In other words, `decodeToCanvas()` is upstream of `decode()`. It's more flexible for us to have the underlying `canvas` because then we can simply get a BLOB and handle it with our existing function to insert the BLOB URL into the DOM.

See https://github.com/chase-moskal/webp-hero/blob/master/source/webp-machine.ts#L106

**Comment by chase-moskal** [comment]
:tada: `webp-hero@0.0.2` now auto-detects a default value for `useCanvasElements`, allowing it to work out-of-the-box on icecat and other browsers

- this is detected by the [new `detectCanvasReadingSupport` function,](https://github.com/chase-moskal/webp-hero/blob/master/source/detect-canvas-reading-support.ts#L10) which i've made directly available since you folks aren't using this auto-detection via `webpMachine.polyfillDocument()`

    this function will return `true` or `false`, indicating whether or not the browser allows reading data from a canvas, thus letting us know if we need to use the canvas replacement workaround

- data url webp images are now supported, thanks to the [new `improvedWebpImageDetector` function,](https://github.com/chase-moskal/webp-hero/blob/master/source/webp-machine.ts#L22) which is also exposed if you'd like to use it

- more changes are outlined in [the changelog](https://github.com/chase-moskal/webp-hero/blob/master/CHANGELOG.md)

**Comment by Jaifroid** [comment]
Wow, you rock @chase-moskal! I'll try these out: it will simplify our code, and will also help with Service Worker mode where I think polyfillDocument() is used (your polyfill is included in the ZIM).

**Comment by chase-moskal** [comment]
@Jaifroid

sorry about the confusion.

- if you're using the bundle, like from a script tag like this:
    ```html
    <script src="https://unpkg.com/webp-hero@0.0.2/dist-cjs/webp-hero.bundle.js"></script>
    ```
    then you'll find `detectCanvasReadingSupport` on the global object:
    ```js
    const support = window.webpHero.detectCanvasReadingSupport()
    ```
- if instead you're using common-js, you can `require` the function itself:
    ```js
    const {detectCanvasReadingSupport} = require("webp-hero")
    const support = detectCanvasReadingSupport()
    ```
    - or even more directly:
        ```js
        const {detectCanvasReadingSupport} = require("webp-hero/dist-cjs/detect-canvas-reading-support.js")
        const support = detectCanvasReadingSupport()
        ```
- if you're using es modules, you can `import` the function:
    ```js
    import {detectCanvasReadingSupport} from "webp-hero"
    const support = detectCanvasReadingSupport()
    ```
    - or even more directly:
        ```js
        import {detectCanvasReadingSupport} from "webp-hero/dist/detect-canvas-reading-support.js"
        const support = detectCanvasReadingSupport()
        ```

**Comment by Jaifroid** [comment]
Thanks @chase-moskal , I've now incorporated the new detection function into the PR:

Interestingly, when testing the new implementation, after having manually disabled it, when I turned it back on I got a the popup below appearing in IceCat. It seems the IceCat browser contains an option to disable the anti-fingerprinting on a per-domain basis. But it's clearly not well exposed, as this is the first time I've seen it. It appears to be exposed by the testing technique.

![image](https://user-images.githubusercontent.com/4304337/154799133-f197df19-50ce-485b-87f4-545093aa17d8.png)

**Comment by Jaifroid** [comment]
And indeed, if I answer "Allow data access" to that question (though I unchecked Always remember my decision, so that I can continue testing), then the webpHero detect function returns true (i.e. workaround not needed), and images load OK...

**Comment by Jaifroid** [comment]
OK, it turns out that IceCat provides a way to turn off the canvas blocking. User needs to click the little image icon (circled in screenshot below), and turn it off. I wish we'd known this earlier!

@mossroy Do you want to keep #838 ? I think we should definitely upgrade to use the latest WebpHero. An argument in favour is that the detection is generic, so it may apply to other browsers or browsers that have an extension that blocks canvas fingerprinting. Clearly they'd have to be old browsers that don't support WebP natively to use this. An other argument in favour is that it took us a long time to find this setting by accident, whereas with the workaround detection, it works "out of the box". But it's up to you!

![image](https://user-images.githubusercontent.com/4304337/154799747-f15361c9-1c90-44d9-bd79-b9e781ee69e5.png)

**Comment by Jaifroid** [comment]
@chase-moskal A big thank you for your super-rapid response on this issue, adding all this support upstream in the Polyfill. It's been very good to collaborate with you across these projects!
