### ISSUE TITLE
Need an option to disable drag-and-drop

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-js#966]
I need an option to disable drag-and-drop. That feature keeps getting activated on my computer when I already have a zim open and am reading it. It causes me to lose my place and distracts me when I have to find where I was.

On my computer I have the following problems:
- '\0' is typed into browser windows when tabbing to switch from Konsole
- Alt-tab is sometime interpreted as starting a drag-and-drop
- Drag-and-drop/paste sometimes breaks on Discord/GitHub/Brightspace with ~~`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0`~~ `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0` until I detach the tab into a new window
- Copying text on another computer paired over KDE Connect causes kiwix-js drag-and-drop to activate
- I like to click on text when reading, and accidentally dragging it sends me to the configure page
- Copying text from the zim succeeds, but immediately sends me to the configure page
- Locking-then-unlocking the screen causes the same problem
- These problems don't occur when I have my browser window switched to another tab

It doesn't happen on a fresh browser windows, but I have found that the following reproduces it reliably:
1. Open another desktop window such as Konsole
2. Open Firefox (on `kwin-wayland 4:5.27.0-0ubuntu1~ubuntu22.10~ppa1`, and the problem does not occur if `WAYLAND_DISPLAY` is unset)
3. Go to https://en.wikipedia.org/wiki/Main_Page
4. Select "Welcome"
5. Drag it anywhere
6. Open kiwix-js in Firefox
7. Open a zim
8. See that we are on the "Home" tab
9. Press Alt-tab twice
10. See that we are on the "Configure" tab

There are a lot of things currently broken with my setup, but other websites work. Therefore, I would like an option to disable drag-and-drop so that kiwix-js would work like other websites.

**Comment by Jaifroid** [comment]
@danielzgtg This should be doable. We can add a simple param that tells the code not to set up drag-and-drop. Can I check whether you're using Firefox or Chromium? Also, if using Firefox, are you using it in Service Worker mode? The reason I ask is because it would be easiest for you to test whether the fix is effective if I update the code on the server that the Firefox extension accesses (when online). Otherwise, you would have to wait till a new release to test it unless you are prepared to clone the Repo and load a test version of the extension.

**Comment by danielzgtg** [comment]
Yes, I'm on Firefox with the version stated above. And also yes, I'm in Service Worker mode (https://moz-extension.kiwix.org/).

**Comment by Jaifroid** [comment]
Apologies, I was reading too fast, so missed you'd already said you were using Firefox, but useful to know it's in SW mode, because it will make testing much easier. I'll let you know when I've added that option for testing.

**Comment by Jaifroid** [comment]
@danielzgtg Could you kindly visit https://kiwix.github.io/kiwix-js/www/index.html in the same Firefox browser you use? Please look at the bottom of the page under Expert Settings, and tell me if you see an option "Disable drag-and-drop". It should be visible UNLESS you have visited this site in the last couple of months, in which case your browser will have cached the previous code, and I will have to update the version number to force your browser to download new code.

If you do see the option, please try it out, and tell me if it fixes your issue. If the page doesn't visibly reload after you select the disable option, then you will have to exit the app and reload it again (by visiting https://kiwix.github.io/kiwix-js/www/index.html) in order to apply the new setting.

If it works in this test version, then I'll consider how best to roll it out to the moz-extension server as an interim release.

**Comment by danielzgtg** [comment]
Thank you for implementing this.

I see the new checkbox. The same problem occurs before checking it. After checking it and agreeing to reload, the problem is fixed!

**Comment by Jaifroid** [comment]
OK, great! That version will remain in place while I finalize the PR and decide how/when to update the moz-extension version. It should work offline, as it will have cached its own code. I'll let you know here when the moz-extension update is ready.

**Comment by Jaifroid** [comment]
@danielzgtg The PR has now been merged to master and has been pushed to the moz-extension PWA version. Once that version has self-updated to v3.7.2, you'll be able to use the fix in the Firefox extension. It should notify you approximately 10s after launch that the update is available. Simply exit the app and relaunch it, and verify that it has updated to v3.7.2 (top left). Let me know of any issues.

**Comment by danielzgtg** [comment]
It works, thank you!

It showed a box notifying me about the update, but the number and the box stayed the same after 3 refreshes. Then I just pressed "Reset App" to get it to work.

**Comment by Jaifroid** [comment]
OK, great, yes sometimes it takes a reset to fully update, or a restart of the computer. I think what might be happening is that the browser engine is still running in the background, and has not fully quit.
