### ISSUE TITLE
Update references to emscripten/emsdk

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-js#980]
Within https://github.com/kiwix/overview/issues/82, we looked at all repos for dependency on Docker Images that may migrate out of Docker Hub.

You use `emscripten/emsdk:2.0.25` in compilation scripts. [emscripten](https://hub.docker.com/u/emscripten) is a *Community Organization*.

While this specific image shall remain available (unless emscripten decides to), it is possible that emscripten decides to push future images to a different registry (alternatives being to pay a subscription to Hub or get accepted in their OSS Program).

You should probably find out what will happen and adjust your scripts accordingly.

**Comment by Jaifroid** [comment]
Thank you for checking this. I'll find out what Emscripten's plans are. This will probably affect WASM building in openzim/javascript-lbzim too.

**Comment by kelson42** [comment]
@Jaifroid what is the purpose od this container image?! I though that emscripyen happens now in kiwix-build!

**Comment by Jaifroid** [comment]
Yes, these are probably the main blockers- the first of these is the most serious, and the other two depend on resolving that one:

 * https://github.com/openzim/javascript-libzim/issues/43
 * https://github.com/openzim/javascript-libzim/issues/17
 * https://github.com/openzim/javascript-libzim/issues/11

We would also need to tweak for performance, as it's currently quite a bit slower than XZ / ZSTD access on a modern PC, and unacceptably slow on underpowered devices. But I imagine there are optimizations that could be done.

**Comment by kelson42** [comment]
@Jaifroid Two points:
* The two first bullet points seem to be really similar tickets. They basically talk about atomic/pthreads. This seems to me basically the same technical problem. My problem is that I have no clue about the quality/quantity of the user impact. What is clearly the impact for our audience (client portfolio in biz world) if we decide to not fix this problem?
* We could easily address the third bullet IMO. @mgautierfr you confirm?

**Comment by Jaifroid** [comment]
Yes, we have #770 to take forward the use of libzim for reading articles and assets, which I intend to integrate as an opt-in test version when I get the chance. But I do think that **currently** two few browsers and platforms support Atomic operations in JS, and that if we can get an option to deisable pthreads in libzim, it will widen the catchment significantly.

**Comment by kelson42** [comment]
> But I do think that **currently** two few browsers and platforms support Atomic operations in JS, and that if we can get an option to deisable pthreads in libzim, it will widen the catchment significantly.

Sorry if I highjack a bit #770, but do we have numbers to support this last assertion?

**Comment by Jaifroid** [comment]
If you mean numbers of users affected, I don't know for sure how many users are stuck on such browsers or frameworks, but a good example would be all users of the Windows Store (UWP) app, especially the base app and WikiMed, which are the most used, who are currently unable to access the libzim reader due to lack of Atomics support.

**Comment by kelson42** [comment]
Yes, I mean number of user affected.

Regarding UWP, this is an old or a moderm framework? Do we have an alternative with similar features?

**Comment by Jaifroid** [comment]
UWP is a modern framework but HTML/JS apps use the Edge HTML engine (which doesn't support Atomics) instead of the new Edge Chromium engine. There are some solutions around for changing that, but they're all still experimental. Microsoft reports 30,000 acquisitions of Kiwix JS UWP (of which 6K in the last year) and 15,800 acquisitions of WikiMed by Kiwix UWP (of which 3K was in the last year). Wikivoyage is smaller.

NB I'm not saying that we must remain stuck in the past, but I'd like to keep code that supports legacy situations while introducing new features for users that can run them. It's been the philosophy of Kiwix JS and its derivatives for a long time, and it means everything is supported from IE11 and IceCat, Firefox OS, Edge Legacy, Windows Mobile, 32-bit Linux, Windows from XP to 11, Safari on iOS.... Mossroy was particularly proud of this wide support, and I'd really like to keep that legacy as long as possible, though I'm of course open to dropping things that are not used.

If we can't compile libzim for older targets without Atomics, then so be it, and libzim features will be for clients that can support them. For now, the main difference is better search with libzim.

**Comment by kelson42** [comment]
Then I guess we will have to live with this dependence for a while. I propose then to close this ticket.

**Comment by Jaifroid** [comment]
We should keep this ticket open till I have found out where Emscripten will be publishing its container images.

**Comment by rgaudin** [comment]
> We should keep this ticket open till I have found out where Emscripten will be publishing its container images.

Docker Hub eventually decided to cancel its move so it's likely that emscripten will not do anything if they didn't already start a migration.

**Comment by Jaifroid** [comment]
I think it's safe to close this now.
