### ISSUE TITLE
Failed test for the zim file of FreeCodeCamp

### ISSUE THREAD

**Issue by RavanJAltaie** [kiwix/kiwix-js#997]
Hi, the test file for FreeCodeCamp is not working properly, I've attached some screenshots of what's appearing in Kiwix Reader when I open the file.
I opened the file using Kiwix Reader in Chrome. 
<img width="956" alt="1" src="https://user-images.githubusercontent.com/116940574/234828042-c09be4f0-7d70-48b7-b325-1c7af860d751.png">
<img width="944" alt="2" src="https://user-images.githubusercontent.com/116940574/234828046-8b461ac3-c415-43e2-a5ff-1dd87e6f60af.png">
<img width="944" alt="3" src="https://user-images.githubusercontent.com/116940574/234828053-9f577479-f640-436d-867f-13f9ea0b22b5.png">

**Comment by Popolechien** [comment]
Note: spoke to @RavanJAltaie and I believe this is on Windows. I'm using Kiwix-JS on Chrome as well, but macOS and things work fine on my end. @Jaifroid any idea how this can be?

**Comment by Jaifroid** [comment]
@RavanJAltaie You're using Kiwix JS PWA version (which is a bit different to the browser extension). Does it work in the browser extension (for [Chrome](https://chrome.google.com/webstore/detail/kiwix/donaljnlmapmngakoipdmehbfcioahhk), [Firefox](https://addons.mozilla.org/en-GB/firefox/addon/kiwix-offline/) or [Edge](https://microsoftedge.microsoft.com/addons/detail/kiwix/jlepddlenlljlnnhjinfaciabanbnjbp))? If you can give me a link to the FreeCodeCamp ZIM, I'll test to see what's going on in the PWA version.

**Comment by RavanJAltaie** [comment]
@Jaifroid I'm using the chrome browser extension

**Comment by Jaifroid** [comment]
@RavanJAltaie The Chrome browser extension version doesn't have those icons and compact toolbar. It should look like screenshot below.  That's https://pwa.kiwix.org, or else you could be using the Electron app.

![image](https://user-images.githubusercontent.com/4304337/234832245-725e448b-2912-4a3a-ab99-00aae90dac7b.png)

But if you can provide me a link to the ZIM, I'll investigate. I couldn't find it searching for "freecodecamp" or "free code camp" on library.kiwix.org, and a quick search through download.kiwix.org didn't find it either (but there are lots of directories, and I didn't look in all of them).

**Comment by Popolechien** [comment]
@jaifroid I'll send you the test zim on slack

**Comment by Jaifroid** [comment]
OK, I've tested (using Chromium 112 on Windows), and I'm not seeing any error in either the PWA (top two screenshots) or in the Chrome extension (bottom screenshot). @RavanJAltaie Please be sure you are running the app in ServiceWorker mode (not JQuery). Also, it might be worth resetting the app: in the PWA there is a button under "Troubleshooting and Development", and in the browser extension, you'll see a similar button under "Expert Settings". That should ensure we're testing the same configuration. One issue I notice with the ZIM is a poorly executed Dark Theme that I don't have the option to turn off in the UI (my system is set to "Dark", and clearly the scripts recognize this and apply an automatic Dark Theme which is not too good, because text boxes are not properly themed).

![image](https://user-images.githubusercontent.com/4304337/234840948-ca8a0dcd-7f7d-46c2-9c3c-731e19bb26c1.png)

![image](https://user-images.githubusercontent.com/4304337/234841047-313d4022-6077-4c76-8d76-0b75751df611.png)

![image](https://user-images.githubusercontent.com/4304337/234841074-9dbad268-18ef-486a-92c9-12338085d28d.png)

**Comment by Jaifroid** [comment]
@RavanJAltaie To be sure we're testing the same thing, you can also test in your browser by going to:

https://pwa.kiwix.org (for the PWA, but make sure other instances of the PWA are closed, as it doesn't cope too well with two instances open);

https://moz-extension.kiwix.org/ (for a pure version of the browser extension, not wrapped in extension code).

**Comment by Jaifroid** [comment]
So I don't think there's anything to fix here, but feel free to re-open if you're experiencing issues with this codebase.
